### ISSUE TITLE
Define a custom Swift 4 Encoder to write the models

### ISSUE THREAD

**Issue by pepibumur** [tuist/xcodeproj#100]
## Context 🕵️‍♀️
To serialize the project back to disk, we defined a class `PBXProjWriter`, that does a custom property list writing, including comments for some elements *(this is the format that Xcode uses for the projects)*.

## What 🌱
Figure out if it's possible to use the protocol Encoder, and define a custom encoder that contains that logic. That'd get the writer closer to the language syntax and developers would me more familiar with it.

## Proposal 🎉
- Investigate how Encoders are implemented.
- Evaluate if it's feasible to move the writer into an Encoder.

**Comment by yonaskolb** [comment]
@pepibumur I don't see the point of this stale bot. We don't have hundreds of issues that are overwhelming, and these are ones we want to keep open

**Comment by pepibumur** [comment]
Removed @yonaskolb

**Comment by pepibumur** [comment]
I don't think there's a lot of value on this task other than doing it the Swifty way. Our consolidated approach for serializing the in-memory representation of the projects, workspaces, and schemes is working pretty well.

Trying to use encoders wouldn't save us any line of code because objects have custom logic to for the attributes comments that we'd need to support somehow from the encoders. I don't think trying to come up with an abstraction using encoders is worth the effort.

If there isn't any objections to this, I'll close the issue.
