### ISSUE TITLE
Auto generation of schemes

### ISSUE THREAD

**Issue by esttorhe** [tuist/xcodeproj#115]
## Context 🕵️‍♀️
The scheme window in `Xcode` provides a checkbox to autogenerate schemes.
This are stored `project.xcodeproj/xcuserdata/<username>/schemes` and since they are specific to each user not usually carried over on repos, etc.

<img width="316" alt="screen shot 2017-10-13 at 12 28 45" src="https://user-images.githubusercontent.com/2642850/31542392-16ffedf0-b012-11e7-9c75-348d19410ced.png">

## What 🌱
This is a 2 fold issue:

1. `xcproj` doesn't handle the flag (e.g. if we read a project and then save it we are not carrying over said flag) `IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded` located in `Fixtures/iOS/Project.xcodeproj/project.xcworkspace/xcshareddata/<username>/WorkspaceSettings.xcsettings`. We should handle this since its part of the shared data
1. Do we want to support the autogeneration of schemes? 

## Proposal 🎉
I think the first point we should address definitely; the second I'm not entirely sure if is something that should fall under the responsibility of `xcproj`; maybe something that falls under [XcodeGen](https://github.com/yonaskolb/XcodeGen) ?

**Comment by pepibumur** [comment]
Good point. I think we should support the first one. Regarding the second one, we should at least support writing the file that contains that configuration. The creation of the scheme and its data is responsibility of the tool that generates the scheme. What do you think?

**Comment by esttorhe** [comment]
I agree; ultimately the file that contains the configuration is a `plist` with a single key:value pair.

Haven't found any other possible setting that could end up in that file but supporting it with a single value for now sounds 👌

**Comment by pepibumur** [comment]
:shipit:

**Comment by yonaskolb** [comment]
This is something that came up recently in XcodeGen. It would be great to have access to this file to turn off the `IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded` flag.
cc @rahul-malik
