### ISSUE TITLE
Not finding .pbxproj

### ISSUE THREAD

**Issue by Lancelotbronner** [tuist/xcodeproj#236]
## Context 🕵️‍♀️
I am using macOS High Sierra v10.13.3. I implemented xcproj first with cocoapods but there were errors with AEXML's framework so I simply copied all files into a directory in my project.

## What 🌱
When initializing an XCodeProj (exactly like in the example), it returned nil. I checked that the path was right (it was), that the project.pbxproj was there (it was), etc. I debugged the problem all the way there:

XCodeProj.swift, init(path:), line 21
`let pbxprojPaths = path.glob("*.pbxproj")`
It returned one path whose url was "/".

So the initializer left on the line 25, as there was no data to find I guess.
`let pbxProjData = try Data(contentsOf: pbxprojPaths.first!.url)`

I wasn't sure wether to post the issue in PathKit (since the problem seems to be coming from there `glob` function), so I posted it in the two in case.

**Comment by olbrichj** [comment]
Just a quick question. Did you disable the sandbox in your projects entitlements? Otherwise your app won't have access to the filesystem and won't find the project.

**Comment by Lancelotbronner** [comment]
Hello!
Thank you for the quick response!

I will check that during the week, but I don’t think there are project entitlements in a command line tool.

Thank you!

**Comment by Lancelotbronner** [comment]
Hello!

I can confirm I do not have project entitlements anywhere in my project.

Thanks!
Christophe Bronner

**Comment by pepibumur** [comment]
Hi @Lancelotbronner. Could you solve this issue that you had with xcproj?

**Comment by Lancelotbronner** [comment]
Hello,

I have updated some stuff and I think the problem went away, I will confirm that with you once it’s back up and running or when I get errors from xcproj.

Thanks,
Christophe Bronner

**Comment by pepibumur** [comment]
Would you mind adding some concrete examples @Lancelotbronner. That'll help us better know what's exactly failing on those examples.

**Comment by pepibumur** [comment]
Thank you very much @Lancelotbronner I'll debug those on Monday and fix them.

**Comment by pepibumur** [comment]
@Lancelotbronner would you mind trying with the latest version of the library?
