### ISSUE TITLE
Shaping the future of xcproj

### ISSUE THREAD

**Issue by pepibumur** [tuist/xcodeproj#256]
Hey everyone!

Almost one year ago I started working on xcproj. It's been an exciting journey so far, with ups and downs, but encouraging seeing all of you using the library, building tools and automating things in your own projects. After all the feedback I've collected from issues, PRs, and on Slack I thought it'd be a good idea to iterate and improve the tool and its API, and take the opportunity to wok on some things that have been in the backlog for some time. I'd like to share with you a rough plan of how I see the next version of xcproj at the project and the organization level and get some feedback from you.

### Major improvements
- **Automatic reference generation:** Generating references for every new element that gets added to a project is cumbersome. Other libraries like [xcodeproj](https://github.com/cocoapods/xcodeproj) from CocoaPods prevents users from having to do so. We'd leverage Sourcery to provide a new method from the project objects that returns a deterministic and unique reference of themselves.
- **Equatable:** Not all the classes in the project conform to the `Equatable` protocol. Similarly, we'd use Sourcery to conform Equatables from the models that don't conform it yet.
- **Convenience API:** After having used xcodeproj from CocoaPods and seeing feedback from you I realized there's a lot that we can improve to make the API more convenient and easy to use. The current API requires developers to have certain knowledge in the project structure, like the fact that build phases reference files throw a proxy object, `PBXBuildFile`. My goal is to revisit all the models and provide easy-to-use and convenient methods from their interfaces. This requires two major changes:
  - Objects need a weak reference to the project they belong to.
  - References from objects to other objects need to be memory pointers rather than strings. That way we can safely update the reference values (strings) without breaking refeferences from other objects.

### Minor additions
- **Constants:** There are certain constants associated with the creation of Xcode projects that we could provide from xcproj. Some examples of those constants are the default projects build settings or the Xcode file type from the file extension.
- **SPM Packages:** Replace shell and path libraries with the tools existing in the Swift Package Manager. By doing this we not only reduce the number of dependencies but align the tool with Apple's paradigms and tools.
- **Documentation:** Although we've tried to keep the documentation up to date, it needs a revisit and the introduction of some checks to make sure future contributions are well documented.
- **Linux compatibility:** xcproj is only compatible with the macOS environment. We are only one step from having also support for the linux environment.
- **Code coverage:** Add code coverage checks with codecov to ensure a good coverage when new code gets added to the repository.
- **Guided releases:** Automating the release process so that it can be run from continous integration. The role of "release captain" would still be necessary but the person would just check that the release runs smoothly on CI.

### Organization
- I propose renaming the project and the org to `xcodeproj`. The same project for other platforms have that name and I think it's a good idea being consistent. It'll make it easier for people to find it searching on Google or GitHub. Moreover, the development of some experimental tools like `Sake` and `xctools` have been discontinued, that means the main project of the organization is `xcproj`. I propose renaming the organization as well to `xcodeproj` and narrow its focus to build a **reliable** and **easy to use** Xcode project parser. As a side note if anyone is interested in continuing the development of Sake, xctools or xclint we can transfer those repositories to their account.
- **Close the Twitter account.** We haven't had much activity there and I don't think it brings that much value to the organization as to keep it open.
- **Core contributors:** I'd like to revisit what being a core contributor means and find people commited to being one. In my opinion a core contributor should help with triaging new issues, reviewing new PRs or releasing new versions of the tool. If anyone is particularly interested, send me a message on Slack or via email, [pepibumur@gmail.com](mailto://pepibumur@gmail.com).

Having said that, I'm looking forward to getting your feedback and starting working on the future of xcodeproj. It's going to be amazing, and with help we'll help a lot of projects and companies deal with their Xcode projects.

cc @xcodeswift/contributors

**Comment by alvarhansen** [comment]
Thank you @pepibumur for xcproj and all the hard work and time you have put into it. This project has saved me and others a lot of time and sanity (mostly around pbxproj git conflicts).
It's great to see that you have big plans for this project.

Some thoughts on organisational topic:

* **Renaming the project.**
Wouldn't it make it harder to find this specific project if was called the same as Cocoapods/xcodeproj ?
For example if someone were to ask question in StackOverflow and mention that they use `xcodeproj`, first question would be: "Which one?".

  If you do rename it, I recommend immediately creating new organisation and project with the same name and leaving the latest state of project there. This way you don't breaks a lot of CI pipelines around the world.

* **Twitter account.**
Well, the readme does lead to 404, so that may be a problem with small activity around it 😄 


With new Xcode we saw some changes to project format. Going forward, do you see xcproj supporting multiple versions of project format or only the latest?

**Comment by pepibumur** [comment]
Thanks for your answer @alvarhansen and glad to hear that it's been very helpful for you.
- **Renaming of the project:** I hadn't think about that but that's a good point actually. What about introducing the swift keyword somewhere? I'd be too long I think `xcodeproj-swift`. Something that we can do when we rename it, and I've seen it in other projects like ReactiveCocoa, is creating a major version that includes the renaming. That way we don't break CI pipelines.
- **Twitter account:** I hadn't noticed that actually. Do you think it's valuable to see tweets from that account? Which kind of information would you like to read from it?

I think it's ok with continuing the support as we have been doing it so far.  With supporting the latest version we'd support the previous versions because changes in Xcode projects are usually incremental.  That's how CocoaPods does it with `xcodeproj`.

**Comment by yonaskolb** [comment]
Sounds good. Though I agree that the name change is perhaps unnecessary and potentially quite confusing, due to it already being an established name

**Comment by pepibumur** [comment]
Most of the points above have been addressed:

- [x] Automatic reference generation. There's a little thing missing that I need to implement.
- [x] Convenient API. Objects have methods now to materialize references to other objects. You don't need to look up those objects in the project.
- [x] There's a `Xcode` class with some constants and helper methods defined in it.
- [x] SPM Packages: The only dependency now is the Swift Package Manager utils frameworks.
- [x] Add code coverage reports.
- [x] Rename project to `xcodeproj`.

**Missing**
- [ ] Review documentation.
- [ ] Guided releases.
- [ ] Conform the `Equatable` protocol from the scheme models.

Although the new version hasn't been released yet, you can start migrating your projects using the migration [guidelines in the README](https://github.com/xcode-project-manager/xcodeproj#migrate-to-xcodeproj-5)

I'll continue working in the missing stuff to get the first alpha out next week.

**Comment by pepibumur** [comment]
I merged yesterday the last task that was missing, conforming equatable from the scheme models. I took the opportunity to refactor the `XCScheme` file and split it into smaller and more manageable files. I'll release another candidate today.
