### ISSUE TITLE
PBXObjectReference property names

### ISSUE THREAD

**Issue by yonaskolb** [tuist/xcodeproj#286]
Post 5.0 the properties referencing `[PBXObjectReferences]` have `References` appended to them. There are some cases of this causing grammatical errors due to pluralization. eg:
- buildPhasesReferences
- buildRulesReferences
- targetsReferences
- dependenciesReferences
- buildConfigurationsReferences

These could be renamed to remove the pluralisation.
However I would suggest however actually removing the `References` suffix from all these properties (and other single references like `buildConfigurationListReference`). This has several advantages:
- better matches the actual properties in the `project.pbxproj`
- removes a lot of breaking api changes by moving property names back to how they were
- removes the redundant type name from the property name (before this change `children` wouldn't be called `childrenStrings`)

Thoughts?

**Comment by yonaskolb** [comment]
Yeah that's one option. What if they had the original names and you just had an extension on an array of PBXObjectReference that had an `objects` property? That way it's still easy to use, but you don't have to duplicate all the properties

**Comment by pepibumur** [comment]
That could be another option but the `objects` property would either return `PBXObject` or a generic type that developers would need to cast into the type that the reference is referring. That's something that could be solved by making the `PBXObjectReference` class generic, but that'd introduce another set of problems when using them in collections.

I think it's fine having typed getters for those references, there are not that many.

**Comment by yonaskolb** [comment]
I'm ok with that approach 👍
