### ISSUE TITLE
Lots of warnings in Xcode 10

### ISSUE THREAD

**Issue by drekka** [tuist/xcodeproj#303]
Looks like the bulk of them are retired features of Xcodeproj that are still being used internally.

**Comment by pepibumur** [comment]
We are addressing that [here](https://github.com/tuist/xcodeproj/pull/300). We deprecated some public methods that used internally. That PR will require a major bump because it introduces some breaking changes.

**Comment by pepibumur** [comment]
It's already been merged. Check out the [release notes](https://github.com/tuist/xcodeproj/releases/tag/6.0.0) and the [migration guidelines](https://github.com/tuist/xcodeproj#migrate-to-xcodeproj-6) for more information.

**Comment by drekka** [comment]
Got it thanks.
