### ISSUE TITLE
Compile error in release builds

### ISSUE THREAD

**Issue by yonaskolb** [tuist/xcodeproj#304]
It seems Swift 4.2 is failing to build xcodeproj in release mode for some reason.
This can be seen by running:
```
swift build -c release
```

The following error occurs
```
PHI node operands are not the same type as the result!
  %159 = phi %Ts23_ContiguousArrayStorageCySSG* [ %336, %328 ], [ %143, %481 ], [ %143, %470 ], [ %143, %454 ], [ %143, %438 ], [ %143, %423 ], [ %143, %146 ]
<unknown>:0: error: fatal error encountered during compilation; please file a bug report with your project and the crash log
<unknown>:0: note: Broken function found, compilation aborted!
0  swift                    0x000000010e76664a PrintStackTraceSignalHandler(void*) + 42
1  swift                    0x000000010e765dfe SignalHandler(int) + 302
2  libsystem_platform.dylib 0x00007fff7908df5a _sigtramp + 26
3  libsystem_platform.dylib 0x000000011b583600 _sigtramp + 2723108544
4  libsystem_c.dylib        0x00007fff78e2b1ae abort + 127
5  swift                    0x000000010a9edaf7 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*)::$_1::__invoke(void*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) + 519
6  swift                    0x000000010e71a278 llvm::report_fatal_error(llvm::Twine const&, bool) + 280
7  swift                    0x000000010e71a15b llvm::report_fatal_error(char const*, bool) + 43
8  swift                    0x000000010e6e17e6 (anonymous namespace)::VerifierLegacyPass::runOnFunction(llvm::Function&) + 54
9  swift                    0x000000010e68804e llvm::FPPassManager::runOnFunction(llvm::Function&) + 446
10 swift                    0x000000010e690363 llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) + 115
11 swift                    0x000000010e690258 llvm::legacy::FunctionPassManager::run(llvm::Function&) + 392
12 swift                    0x000000010abb4228 swift::performLLVM(swift::IRGenOptions&, swift::DiagnosticEngine*, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, swift::version::Version const&, llvm::StringRef, swift::UnifiedStatsReporter*) + 4504
13 swift                    0x000000010abb8e0e ThreadEntryPoint(swift::irgen::IRGenerator*, llvm::sys::SmartMutex<false>*, int) + 206
14 swift                    0x000000010abb8e6f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(swift::irgen::IRGenerator*, llvm::sys::SmartMutex<false>*, int), swift::irgen::IRGenerator*, llvm::sys::SmartMutex<false>*, int> >(void*) + 47
15 libsystem_pthread.dylib  0x00007fff79097661 _pthread_body + 340
16 libsystem_pthread.dylib  0x00007fff7909750d _pthread_body + 0
17 libsystem_pthread.dylib  0x00007fff79096bf9 thread_start + 13
Stack dump:
0.	Running pass 'Module Verifier' on function '@"$S9xcodeproj12PBXBuildFileC16plistKeyAndValue4proj9referenceAA15CommentedStringV3key_AA05PlistG0O5valuetAA7PBXProjC_SStKFTf4dxn_n"'
<unknown>:0: error: unable to execute command: Abort trap: 6
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
```

This is a blocker for XcodeGen and there is an open issue here https://github.com/yonaskolb/XcodeGen/issues/391

**Comment by pepibumur** [comment]
Thank for opening it. I realised it the other day doing some tests with Xcode 10 but I haven't been able to work on it yet. I'll prioritize this :)

**Comment by pepibumur** [comment]
Thanks for reporting it. Do you have the link to the radar @fxcoudert?

**Comment by fxcoudert** [comment]
@pepibumur radars don't have public links, do they?

**Comment by pepibumur** [comment]
🤔 I thought they had. Is there any way to see if they respond to the radar?

**Comment by yonaskolb** [comment]
https://bugs.swift.org would probably be a better place to open a bug. I don't have time to file one right now if someone else could

**Comment by pepibumur** [comment]
[Here](https://bugs.swift.org/browse/SR-8790) is the bug. I tried several things but none of them worked :/

**Comment by pepibumur** [comment]
This trick seems to work with the version 6.0.0 https://github.com/tuist/xcodeproj/commit/386575111ee5d4cae7877b651b695e0e1c4e2740. However, I tried to do the same in 4.3.0 to release a hot fix release, but it doesn't work :/

**Comment by keith** [comment]
Submitted a workaround as well https://github.com/tuist/xcodeproj/pull/307

**Comment by keith** [comment]
I'll prepare a PR for the necessary 4.3.0 change

**Comment by yonaskolb** [comment]
Is there going to be a 6.0.1 release as well?

**Comment by KaneCheshire** [comment]
Can I ask if this fix will be published to Cocoapods? It's still showing as 4.3.0 for me there.

**Comment by pepibumur** [comment]
Hey @KaneCheshire 
I'll publish the 4.3.1 hot fix to CocoaPods but keep in mind that we dropped the CocoaPods support from the project.

**Comment by KaneCheshire** [comment]
@pepibumur good to know! I wasn’t aware of that. Appreciate you taking the time to make an exception in this case. I use the pod in PixelTest: https://github.com/KaneCheshire/PixelTest

Going forwards I guess I’ll need to try and find another way to have it as a pod. 

Thanks!

**Comment by pepibumur** [comment]
No worries. We introduced the Swift Package Manager as a dependency from the version 5+, which doesn't support CocoaPods. I doubt we can tell Apple to support it :trollface:. What we could do though is providing an easy way to generate a dynamic framework with both, the x86 and the ARMv7, that you can integrate into your project using Carthage's approach. Would you mind opening an issue on this project where we can discuss this further?
