### ISSUE TITLE
No way to set target attributes that rely on a reference

### ISSUE THREAD

**Issue by yonaskolb** [tuist/xcodeproj#321]
## Context 🕵️‍♀️
We need to set a target attribute within `PBXProj.targetAttributes` that relies on a reference, namely `TestTargetID`

## Proposal 🎉
Perhaps when setting `targetAttributes` you could use a `PBXObject` as a value (as the dictionary is a `[String: Any]`, and then when writing we'd loop through all the values in the dictionary, and if anything is a `PBXObject` it sets it's reference value instead

**Comment by pepibumur** [comment]
Using the `PBXObject` is a good idea. Internally we should keep the reference because we need to get its value when writing the project.
