### ISSUE TITLE
Delete removes the file reference, but not the referring file references.

### ISSUE THREAD

**Issue by twobitunicorn** [tuist/xcodeproj#324]
Hi.  Loving this library.  I am trying to remove a file reference from an XcodeProject file and I do not understand the results of this.  It seems that all references to the file are not removed when I write the project to file.

Here is a summary of my project.pbxproj file.

```plist
/* Begin PBXBuildFile section */
298D7C871BC2C88F00FD3B3E /* AFNetworkReachabilityManagerTests.m */ = {isa = 
PBXFileReference; lastKnownFileType = sourcecode.c.objc; path = 
AFNetworkReachabilityManagerTests.m; sourceTree = "<group>"; };

2987B0CE1BC40A7600179A4C /* AFNetworkReachabilityManagerTests.m in Sources */ = {isa = 
PBXBuildFile; fileRef = 298D7C871BC2C88F00FD3B3E /* AFNetworkReachabilityManagerTests.m */; };
```

I call the method `project.pbxproj.delete(object: fileReference)` where `fileReference` is for the file reference for `AFNetworkReachabilityManagerTests.m`.  I end up with the project file here

```plist
/* Begin PBXBuildFile section */
		2987B0CE1BC40A7600179A4C = {isa = PBXBuildFile; fileRef = 
298D7C871BC2C88F00FD3B3E; };
```

The reference `298D7C871BC2C88F00FD3B3E` has been removed; however, the reference `2987B0CE1BC40A7600179A4C` is still in the file with only the comments removed.  This file reference is not used by anything in the project nor is the file that it references.  Is there another step I should take here to remove this "ghost" file reference?  Or, is this an issue I can help track down and fix?

Thank again for all your work on this!

**Comment by pepibumur** [comment]
Hi @twobitunicorn. Glad that you liked the library. 

In a nutshell, `PBXBuildFile` is a proxy class between a build phase and a file reference. When you remove the file reference, you remove just the reference to the file, but not any other object that might be referencing that file.

What you should also do is:
- Remove any reference to the file from any group.
- Remove the build file
- Remove the reference to that build file from any build phase.

**Comment by pepibumur** [comment]
There's nothing else to be done on this issue. Closing it.
