### ISSUE TITLE
Request: add settable "parallelized" and "testExecutionOrdering" options to scheme generator methods for TestableReference. 

### ISSUE THREAD

**Issue by sjepifanov** [tuist/xcodeproj#335]
## Context 🕵️‍♀️
> Xcode 10 introduced several options for Test schemes: 
parallelizable = "YES|NO"
testExecutionOrdering = "random"
they reside under TestAction\Testables\TestableReference section of .xcscheme file.

> Using xcodeproj (v4.3.1 included with XcodeGen) to generate scheme for all tests targets.

> These options are implemented in [CocoaPods\xcodeproj](https://github.com/CocoaPods/Xcodeproj/blob/master/spec/scheme/test_action_spec.rb), but we are not using that tool.
 
## What 🌱
>v4.3.1 and latest v6.1.0 only support setting "skipped = YES|NO" to TestableReference section
(XCScheme.swift(4.3.1), XCScheme+TestableReference.swift(6.1.0))

## Proposal 🎉
> Add settable "parallelized" and "testExecutionOrdering" options to scheme generator methods for TestableReference.

**Comment by pepibumur** [comment]
Thanks for bringing this up @sjepifanov. That's something we should definitively add support for.
