### ISSUE TITLE
Issue with adding file to PBXGroup

### ISSUE THREAD

**Issue by Vyeczorny** [tuist/xcodeproj#341]
Hi, I have an issue with adding a file to `PBXGroup`. I'm trying to add file to the group using method:
```
try group.addFile(at: Path(filePath), sourceTree: .group, sourceRoot: Path(projectPath))
```
where:
```
filePath = /Users/username/Documents/Praca/misc/TestApp/TestApp/TestApp/Connectors/TestConnector.swift
projectPath = /Users/username/Documents/Praca/misc/TestApp/TestApp
group.path! = "Connectors"
```

The file is added to the correct group, but the path in the .pbxproj file is wrong (path doesn't contain `Connectors` component):
```
FR_97E519B91B0000E0820899607156CA62 /* TestConnector.swift */ = {isa = PBXFileReference; explicitFileType = sourcecode.swift; lastKnownFileType = sourcecode.swift; name = TestConnector.swift; path = /Users/username/Documents/Praca/misc/TestApp/TestApp/TestApp/TestConnector.swift; sourceTree = "<group>"; };
```

I investigated that it is removed in line 173 of file `PBXGroup`, while creating path to save in pbxproj. Am I doing something wrong?

Thanks for your help,
Karol

**Comment by pepibumur** [comment]
Hi @Vyeczorny. `filePath` should be relative to the group you are adding the file to. If you want to use absolute paths instead, which I don't recommend, you can use absolutePath as sourceTree.

Let me know if that helps :)

**Comment by Vyeczorny** [comment]
I used absolute path only in development process, I will use relative path in final project. However, I think I found some bug, I created a [pull request](https://github.com/tuist/xcodeproj/pull/343), could you take a look on it?

**Comment by pepibumur** [comment]
That's a legit bug. Thanks for adding a fix for it.
