### ISSUE TITLE
Generate XCode style UUIDs

### ISSUE THREAD

**Issue by samskiter** [tuist/xcodeproj#344]
## Context 🕵️‍♀️

We are using [XCodeGen](https://github.com/yonaskolb/XcodeGen) to generate projects.
We are also using [the famous sort script from apple](https://github.com/mas-cli/mas/blob/master/script/sort.pl) to keep our project file sorted and reduce the chances of merge conflicts.

## What 🌱
After generating a project using XCodeGen, we ran the sort scripts and found it failed on line 171. The UUID was not found on a line.

[Tracking this down](https://github.com/tuist/xcodeproj/blob/b1f131b8614a1846b165baa02d7162a3c949ba21/Sources/xcodeproj/Utils/ReferenceGenerator.swift#L299), it looks like this is because XCodeProj generates UUIDs of the format `AAA_123456789123_1` (where AAA is an acronym for the portion of the project file the reference is being generated for and the final _1 is if a reference is already taken).

## Proposal 🎉
Please generate UUIDs in the same format that XCode does in order to keep other tools that make assumptions about the format of UUIDs working. Or provide an option to generate as XCode would.

To achieve this, I imagine you could perform a 24 or 32 byte hash operation on the `reference` variable, here: https://github.com/tuist/xcodeproj/blob/b1f131b8614a1846b165baa02d7162a3c949ba21/Sources/xcodeproj/Utils/ReferenceGenerator.swift#L299

**Comment by samskiter** [comment]
Closing - completely our fault, we are on old XCodeGen and therefore old XCodeProj. Appologies for the noise!

**Comment by samskiter** [comment]
Actually, updating XCodeGen (which uses the latest XCodeProj) we still are getting UUIDs that look like "AAA_123456789". Is that expected?

**Comment by pepibumur** [comment]
cc @yonaskolb

**Comment by pepibumur** [comment]
Closing this one in favor of https://github.com/tuist/xcodeproj/issues/392
