### ISSUE TITLE
OSLogger performance consideration

### ISSUE THREAD

**Issue by toshi0383** [tuist/xcodeproj#348]
I noticed that `OSLogger` is potentially losing a built-in optimization from `os.signpost`.
```swift
    func log(category: String = #file, name: StaticString, _ arguments: CVarArg..., closure: () throws -> Void) throws {
```
https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Utils/OSLogger.swift

- `CVarArg...` causes unwanted memory allocation of an array each time.

In WWDC 2016, Apple says "do not create a wrapper for `os_log` family functions". Maybe it applies to `signpost` too.
<img width="993" alt="screen shot 2018-11-16 at 10 41 01" src="https://user-images.githubusercontent.com/6007952/48592541-30e7f000-e98c-11e8-96ec-c95d507c8475.png">
https://developer.apple.com/videos/play/wwdc2016/721/

Any thoughts?

**Comment by toshi0383** [comment]
`closure` is not escaping, therefore is inlined, so that part is okay.
Maybe adding `@inline(__always)` worths it, but profiling normally happens with Release builds, so it's not mandatory.

**Comment by pepibumur** [comment]
Thanks for bringing this up @toshi0383. 

We can get rid of the wrapper and use the API directly from the places where we log stuff. Not sure what implications it has but if Apple suggested it, they must be doing some optimizations that we are not aware of.

**Comment by toshi0383** [comment]
My college @inamiy came up with this wrapper function. This way we don't waste memory. Maybe it worth trying it. 👌

```swift
func signpost( ..., format: StaticString, _ arg1: CVarArg, closure: () throws -> ()) throws {
    os_signpost(..., format, arg1)
    try closure()
    ...
}

func signpost( ..., format: StaticString, _ arg1: CVarArg, _ arg2: CVarArg, closure: () throws -> ()) throws {
    os_signpost(..., format, arg1, arg2)
    try closure()
    ...
}
```

**Comment by pepibumur** [comment]
That's a good idea @inamiy. Feel free to open a PR with the change. Otherwise, I can tackle it myself next week.
Thanks for helping to improve the library @toshi0383 🚀

**Comment by pepibumur** [comment]
@yonaskolb are you using the metrics provided by those logs? I'm considering the removal of those logs but I want to make sure you are not using them.

**Comment by yonaskolb** [comment]
Nope, not using them. Happy to have them all removed

**Comment by yonaskolb** [comment]
OSLogs removed in https://github.com/tuist/xcodeproj/pull/453
