### ISSUE TITLE
Referencing targets in other projects

### ISSUE THREAD

**Issue by mxcl** [tuist/xcodeproj#352]
I am trying to add dependencies to targets in separate projects.

This doesn't appear to be possible. Specifically the `containerPortal` for the `PBXContainerItemProxy` needs to point to the `PBXFileReference` for the separate project. But `PBXContainerItemProxy` can only have its `containerPortal` set to a local `PBXProject` object.

My question is, is this possible and I’m just doing it wrong?

If it's not possible, I could probably submit a PR to add this functionality. Though I'd need guidance.

Thanks.

**Comment by pepibumur** [comment]
Although it uses references internally the public interface requires you to pass a `PBXProject` instance. That means the project needs to [be part of the projects attribute](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/Project/PBXObjects.swift#L6).

If the project is already there, just pass that reference, otherwise, you need to add it first.

**Comment by mxcl** [comment]
Thanks, that got me further, I wasn't adding the project before, I'm still having trouble however, I have this:

```swift
let mainProject = try XcodeProj(path: projpath)
let cakeProject = try XcodeProj(path: rootpath + Path(".cake/Cake.xcodeproj"))

let mainPBXProject = try mainProject.pbxproj.rootProject()!
try mainPBXProject.mainGroup.addFile(at: rootpath + ".cake/Cake.xcodeproj", sourceRoot: rootpath)
    .explicitFileType = "wrapper.pb-project"

let cakePBXProject = try cakeProject.pbxproj.rootProject()!
mainProject.pbxproj.add(object: cakePBXProject)

let cakeTarget = cakeProject.pbxproj.nativeTargets.first(where: { $0.name == "Cake" })!

for target in mainProject.pbxproj.nativeTargets where target.productType == .application {
    let proxy = PBXContainerItemProxy(containerPortal: cakePBXProject, remoteGlobalID: cakeTarget, proxyType: .nativeTarget, remoteInfo: cakeTarget.name)
    let dep = PBXTargetDependency(name: cakeTarget.name, target: cakeTarget, targetProxy: proxy)
    target.dependencies.append(dep)
    // mainProject.pbxproj.add(object: proxy) //doing this makes Xcode crash (it adds the project as a full object)
    mainProject.pbxproj.add(object: dep)
}
```

I have tried a few other things, to no avail. The resulting pbxproj lacks the `PBXContainerItemProxy` which seems the only thing wrong when I test doing it with Xcode manually like you suggested.

Thanks again.

**Comment by mxcl** [comment]
I tried adapting `PBXNativeTarget.addDependency` so it can take a `project:` parameter then passing `cakePBXProject`, but it gave the same result.

**Comment by pepibumur** [comment]
I think I found the issue. When you run the following line, you get a `PBXFileReference`:

```swift
let projectReference = try mainPBXProject.mainGroup.addFile(at: rootpath + ".cake/Cake.xcodeproj", sourceRoot: rootpath)
    .explicitFileType = "wrapper.pb-project"
```
That reference should be added to this [attribute](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/Project/PBXProject.swift#L71) and the `PBXContainerItemProxy` should be initialized with it. That means that the [`containerPortal` attribute](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/Files/PBXContainerItemProxy.swift#L50) can have a different type depending on the [proxy type](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/Files/PBXContainerItemProxy.swift#L5).

- If the proxy type is reference, then the type of containerPortal should be `PBXFileReference`.
- If the proxy type is referencen, then the type of containerPortal should be `PBXProject`

We can change the signature of the constructor and the property to return a `PBXObject` object instead. What do you think?

**Comment by mxcl** [comment]
Yes, this makes sense, looking for a way to get the `PBXFileReference` into the `PBXContainerItemProxy` is the reason I initially made this post.

> That reference should be added to this attribute

Once I added the PBXProject for project-b to `PBXProject.projects`, the resulting `.pbxproj` *does* contain this, including a correctly populated hidden “Products” group.

**Comment by mxcl** [comment]
I can make the PR here though I find your instructions a little unclear:

> the proxy type is reference, then the type of containerPortal should be PBXFileReference.
If the proxy type is reference, then the type of containerPortal should be PBXProject

I assume you mean `.nativeTarget` for the first one.

And I'm still unclear about how `PBXNativeTarget.addDependency` would work.

**Comment by pepibumur** [comment]
Sorry for not being clear enough:

> I assume you mean .nativeTarget for the first one.

Yes, that's what I meant. I think `type` indicates the type of object that `containerPortal` refers to.

The [PBXNativeDependency.addDependency](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/Targets/PBXNativeTarget.swift#L80) method works only for dependencies between targets in the same project. In that case, `containerPortal` refers to a `PBXProject`. 

You are welcome to open a PR :)

**Comment by mxcl** [comment]
> The PBXNativeDependency.addDependency method works only for dependencies between targets in the same project. In that case, containerPortal refers to a PBXProject.

K that makes sense. Thanks, I'm traveling tomorrow but will try to get this done soon. I need the feature after all, so I have good motivation! Thanks for the help.

**Comment by pepibumur** [comment]
> K that makes sense. Thanks, I'm traveling tomorrow but will try to get this done soon. I need the feature after all, so I have good motivation! Thanks for the help.

Awesome! Thanks for taking your time to do it. We tried to figure out the types and structure of the projects by just changing things in the projcects and looking at the diffs. We fixed many issues in the past but it seems there are still some. I'm glad that you found one of those.

**Comment by mxcl** [comment]
K so it works with a trivial change: 

https://github.com/mxcl/xcodeproj/commit/98936007cf8346b9118175e12b35224bf7b2a4c7

Seemingly everything else necessary was already implemented.

I will improve the API documentation for this change before submitting the PR, unless you have any concerns.

**Comment by pepibumur** [comment]
I'm glad that the trivial change helped. No concerns from my side so feel free to open up that PR.

**Comment by mxcl** [comment]
Just to update here: I have made this work in my fork and will PR as soon as I am able.

**Comment by pepibumur** [comment]
> Just to update here: I have made this work in my fork and will PR as soon as I am able.

That's fantastic. Sorry that I couldn't answer your previous comment, too many things happening during Christmas. I'm looking forward to seeing that PR landing. Thanks for taking your time to improve xcodeproj.
