### ISSUE TITLE
Editing the run phases affects schemes

### ISSUE THREAD

**Issue by kdbertel** [tuist/xcodeproj#356]
## Context 🕵️‍♀️
This is a continuation of #355. I am trying to write a Swift CLI that will add a build phase to run SwiftLint on an arbitrary target in an arbitrary project.

## What 🌱
I have been able to add the phase, and have that show up and run in Xcode. However, it appears that something in the save is not also saving the scheme correctly. In some instances, the scheme disappears entirely from the project; in other cases, it loses the ability to run tests.

My code for doing things (minus front matter for getting arguments) is:
```
let projectPath = Path(projectFile)

guard projectPath.exists else {
    print("Cannot find project file \("\(projectPath)".bold)", to: &stderr)
    exit(EXIT_FAILURE)
}

guard let project = try? XcodeProj(path: projectPath) else {
    print("Cannot read project file \("\(projectPath)".bold)", to: &stderr)
    exit(EXIT_FAILURE)
}

let pbxproj = project.pbxproj

guard let target = pbxproj.nativeTargets.first(where: { $0.name == targetName}) else {
    print("Unable to find target \("\(targetName)".bold)", to: &stderr)
    exit(EXIT_FAILURE)
}

let swiftLintName = "Run SwiftLint"

guard target.buildPhases.compactMap({ $0 as? PBXShellScriptBuildPhase }).filter({ $0.name == swiftLintName }).count == 0 else {
    print("Phase to run SwiftLint already exists. Ignoring.")
    exit(EXIT_SUCCESS)
}

let swiftLintScript = """
if which swiftlint >/dev/null; then
    swiftlint
else
    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
"""

let runSwiftlintPhase = PBXShellScriptBuildPhase(name: swiftLintName, shellScript: swiftLintScript)

pbxproj.add(object: runSwiftlintPhase)
target.buildPhases.append(runSwiftlintPhase)

do {
    try project.write(path: projectPath, override: true)
} catch let error {
    print("Unable to write project: \("\(error)".bold)", to: &stderr)
    exit(EXIT_FAILURE)
}
```

Is there anything else I need to do to the project to guarantee that the scheme remains the same, and that all that's changing is the run phase?

(I have tried doing a diff between the SPM-generated project folder and the one touched by my script, but it ended up being 4300 lines long, the first 1000 or so removed from the `pbxproj` and the other 3000 added, or else I would paste it here)

**Comment by IgorMuzyka** [comment]
@kdbertel have you resolved this issue in some way? Trying to do exactly the same and yeah schemes are changed in a way that xcode sees none.

**Comment by IgorMuzyka** [comment]
Yo @kdbertel managed to solve this easily.
Just traced what mutates schemes and they are rewritten in `write` method of `XcodeProj`.
Since i have no need change the scheme i considered that i only need to use `writePBXProj` method of `XcodeProj`. Like so:
```swift
try! xcodeproj.writePBXProj(
    path: path,
    override: true,
    outputSettings: PBXOutputSettings()
)
```

Still there might something wrong with `XcodeProj` wiping out schemes in project on write.

**Comment by pepibumur** [comment]
First of all, I recommend you doing what @IgorMuzyka suggested. If you are not modifying the schemes, you should write only the `pbxproj` for performance reasons.

From your description though, it seems there's a bug in how schemes are written. Would you mind attaching an example project where you can reproduce the issue? I'd like to investigate this further because the write of scheme should produce the same results if nothing has been modified in them.

**Comment by kdbertel** [comment]
To the best of my knowledge, I'm not actually modifying the schemes in any way. Is there a significant difference between `.write()` and `.writePBXProj()`?

I am still able to reproduce the issue when running against my actual project. Annoyingly, it doesn't seem to crop up when I'm trying to reproduce it in a smaller example. But I'll keep trying to find something.

**Comment by pepibumur** [comment]
> To the best of my knowledge, I'm not actually modifying the schemes in any way. Is there a significant difference between .write() and .writePBXProj()?

- `write` writes the whole project. That includes the pbxproj, schemes, workspace and breakpoints. You can find the implementation [here](https://github.com/tuist/xcodeproj/blob/2b1c9bafb5cc4c39c61de740c916b7676b17be9d/Sources/xcodeproj/Project/XcodeProj.swift#L113).
- `writePBXProj` only writes the `pbxproj` which is the instance that contains the project structure.

Since you are only modifying the structure, you can just call `.writePBXProj`

> I am still able to reproduce the issue when running against my actual project. Annoyingly, it doesn't seem to crop up when I'm trying to reproduce it in a smaller example. But I'll keep trying to find something.

It'd be great if you could find the pattern and attach an example project that I can run some tests on.

**Comment by kdbertel** [comment]
Naturally, as soon as I post about not being able to reproduce it, I'm able to find steps to reproduce.

Attached is my `AddLinting` project.

Steps to reproduce:
1. Unzip `Archive.zip` and `cd` into it
2. On the command line, run `swift build -c release -Xswiftc -static-stdlib`
3. `cd Something; swift package generate-xcodeproj; cd ..`
4. `.build/release/AddLinting "Something/Something.xcodeproj/" "Something"`
5. Open `Something.xcodeproj` in Xcode
6. There are no schemes

An interesting note: this does not happen if the project is opened in Xcode between being generated and running the script to Add SwiftLint. There might be magic that Xcode does?

My use case, though, is that I have a bigger project that I'm working on, and I have a bash script that will regenerate the `xcodeproj` for the SPM module, and then I want to run this `AddLinting` on it before opening it in Xcode, so it's a fully automated process.

**Comment by kdbertel** [comment]
It does appear that moving to `writePBXProj()` solves the issue; the thing I uploaded got halfway there, but then I forgot to delete the other `write()` line 😅

**Comment by IgorMuzyka** [comment]
@kdbertel if you are looking to integrate build phases in xcode generated by SPM here you go my [solution](https://github.com/IgorMuzyka/phase) created today.
I use it like this in my Package.swift of the repo:

Add this to dependency section of `Package.swift`:
```swift
.package(url: "https://github.com/IgorMuzyka/phase", .branch("master")),
```

And then at the bottom add of `Package.swift` define your build phases like this:
```swift
#if canImport(PackageConfig)
import PackageConfig

let config = PackageConfig([
	"phase": [
		"projectPath": "backend.xcodeproj",
		"phases": [
			"SwiftLint": [
				"script": "swiftlint",
				"targets": ["Run"]
			],
			"Generate": [
				"script": "(cd Sources/Core && sourcery)",
				"targets": ["Run"]
			]
		]
	],
])
#endif

```

Will improve Readme sometime later.

**Comment by kdbertel** [comment]
@IgorMuzyka That's a clever solution!

Though I wish that (among other things) the SPM package manifest already included this sort of functionality.

**Comment by pepibumur** [comment]
FYI, I'm fixing this issue on [this PR](https://github.com/tuist/xcodeproj/pull/391)
