### ISSUE TITLE
Explain in the README how to use xcodeproj using swift-sh

### ISSUE THREAD

**Issue by pepibumur** [tuist/xcodeproj#363]
## Context 🕵️‍♀️
[swift-sh](https://github.com/mxcl/swift-sh) makes it easier to run Swift scripts with dependencies. It's a very convenient tool for developers that want to automate certain tasks in their projects using Swift, and they'd like to use xcodeproj as a dependency. cc @mxcl 

## What 🌱
Add a new sub-section in the README that explains how to use `xcodeproj` with swift-sh.

**Comment by mxcl** [comment]
Nice idea, I can tackle this if you’d like?

**Comment by pepibumur** [comment]
> Nice idea, I can tackle this if you’d like?
Go ahead 😛
