### ISSUE TITLE
Replace Codable with a more performant alternative

### ISSUE THREAD

**Issue by pepibumur** [tuist/XcodeProj#369]
## Context 🕵️‍♀️
As suggested [on this issue](https://github.com/tuist/xcodeproj/pull/365), Swift's `Codable` is not the most performant option for parsing the project plist file. Despite having introduced some improvements in that PR, there's still space for improvement.

## What 🌱
Evaluate the available options and replace Codable with he one that provides the best performance. There are companies with large projects that rely on xcodeproj for parsing and generating their projects so they'd benefit a lot from this improvement.

## References
- [Benchmark](https://github.com/bwhiteley/JSONShootout)
- [Marshal](https://github.com/utahiosmac/Marshal)

**Comment by CognitiveDisson** [comment]
I tried to use [DictionaryCoding](https://github.com/elegantchaos/DictionaryCoding) and deleted the extra conversion of dictionaries into raw data. But the results only got worse. (from 3 seconds to 9 seconds)

I also made a small dictionary extension error that reduces performance. I will fix this in the next  PR.

I'll think about how to add measurements tests to catch regressions.

**Comment by pepibumur** [comment]
Sounds reasonable @CognitiveDisson. Thanks for putting effort into making xcodeproj more performant 🙏

**Comment by jcampbell05** [comment]
Not sure if there is a native version but this is what cocoapods uses https://github.com/CocoaPods/Nanaimo if you want to port it

**Comment by pepibumur** [comment]
Since there hasn't been any comment around this being a performance bottleneck, I think we can close this issue. The only reference to this one is from the Linux compatibility effort, and that's something that has already been addressed in recent versions of Swift which already have support for PropertyList decoders in Linux.
