### ISSUE TITLE
Xcode modify attributes for added groups and files in pbxproj

### ISSUE THREAD

**Issue by danilsmakotin** [tuist/xcodeproj#374]
Hi everyone. I use methods of PBXGroup extension `addGroup` and `addFile` for adding a generated source files and an assets to my project:

```
group.addGroup(named: "Generated")

let projectPath = Path("/absolute_path_to_project_dir")
let filePath = Path("/absolute_path_to_project_dir/Generated/GeneratedFile.swift")

group.addFile(at: filePath, sourceTree: .group, sourceRoot: projectPath)

```
The above sample of code produce a result like this in `pbxproj`-file:

```
...
EC6A7A04E554ED26CB606DB47062BCCC /* Generated */ = {
  isa = PBXGroup;
  children = (
    7475EEEFF1E7E06A999ECCE44B35C597 /* GeneratedFile.swift */,
  );
  name = Generated;
  path = Generated;
  sourceTree = "<group>";
};
...
...
...
7475EEEFF1E7E06A999ECCE44B35C597 /* GeneratedFile.swift */ =
{
  isa = PBXFileReference;
  explicitFileType = sourcecode.swift;
  lastKnownFileType = sourcecode.swift;
  name = GeneratedFile.swift;
  path = GeneratedFile.swift;
  sourceTree = "<group>";
};

```

But after changing project file in Xcode, for instance after adding new file manually, Xcode modify it:

```
...
EC6A7A04E554ED26CB606DB47062BCCC /* Generated */ = {
  isa = PBXGroup;
  children = (
    7475EEEFF1E7E06A999ECCE44B35C597 /* GeneratedFile.swift */,
  );
  path = Generated;
  sourceTree = "<group>";
};
...
...
...
7475EEEFF1E7E06A999ECCE44B35C597 /* GeneratedFile.swift */ = {
  isa = PBXFileReference;
  explicitFileType = sourcecode.swift;
  path = GeneratedFile.swift;
  sourceTree = "<group>";
};

```

Xcode has removed `name` and `lastKnownFileType` attributes. 

Now I combine generated and manual approaches for single `pbxproj`-file. It places under git control and this modifications is unwanted for me.

Is it expected behavior? What can I do for solving this problem?

------
xcodeproj version 6.5.0
Xcode version 10.1 (10B61)
macOS version 10.14.2 (18C54)

**Comment by danilsmakotin** [comment]
The second problem is that method `func group(named name: String) -> PBXGroup?` doesn't found groups was created by Xcode, because they have only `path` attribute without `name`.

**Comment by pepibumur** [comment]
Hi @danilsmakotin, thanks for opening this issue. Answering to the issues that you reported:

> Xcode has removed `name` and `lastKnownFileType` attributes.

That's probably what has happened. One question, even though Xcode adds some extra attributes, is the approach using `xcodeproj` working? Optionally you can add the file to the group yourself without using that method. The group exposes a public attribute, children, that you can use for that.

> The second problem is that method `func group(named name: String) -> PBXGroup?` doesn't found groups was created by Xcode, because they have only `path` attribute without `name`.

We can modify [this logic](https://github.com/tuist/xcodeproj/blob/f363129ada081d10548815e53767792acd13b23a/Sources/xcodeproj/Objects/Files/PBXGroup.swift#L111) to take the path into account. Would you be interested in pushing a fix to the project?

**Comment by danilsmakotin** [comment]
@pepibumur thank you for your response. 

> even though Xcode adds some extra attributes, is the approach using `xcodeproj` working?

Now I'm trying to solve a few problems like this one, but in generally this approach works. It's really cool =) I will try applying your advice about manual manipulating with a group's children.

> We can modify [this logic](https://github.com/tuist/xcodeproj/blob/f363129ada081d10548815e53767792acd13b23a/Sources/xcodeproj/Objects/Files/PBXGroup.swift#L111) to take the path into account. Would you be interested in pushing a fix to the project?

Yes, I'm interesting. I will try to create a pull request soon.

**Comment by danilsmakotin** [comment]
It seems like modification of `children` doesn't works correctly now. 

I've changed

`group.addGroup(named: "Generated")`

to
```
let newGroup = PBXGroup(children: [], sourceTree: .group, path: "Generated")
group.children.append(newGroup)
```

After that if I add files to `newGroup` I will get `PBXObjectError.orphaned`.

The following draft of `children`-setter fixes it, but I'm not sure about performance. Also we need to delete a references that was removed from `children`, not only add

```
    public var children: [PBXFileElement] {
        set {
            childrenReferences = newValue.references()
            if let objects = try? self.objects() {
                for child in children {
                    if objects.get(reference: child.reference) == nil {
                        objects.add(object: child)
                    }
                }
            }
        }
        get {
            return childrenReferences.objects()
        }
    }

```

Maybe Is there a better way for solve it? For instance a new method in extension like that:

`public func addGroup(_ group: PBXGroup) throws`

**Comment by pepibumur** [comment]
> After that if I add files to `newGroup` I will get `PBXObjectError.orphaned`.

It's the second time I see this issue being reported so a good indicator of things that we could improve on the API. You are getting the error because you didn't add the group that you created to the project. Try changing your lines to:


```swift
let newGroup = PBXGroup(children: [], sourceTree: .group, path: "Generated")
pbxproj.add(object: group) // <~ This line is missing
group.children.append(newGroup)
```

**Comment by pepibumur** [comment]
I'm closing this issue because there hasn't been any answer since February 27th. If the example that I shared doesn't help, don't hesitate to reopen the issue.
