### ISSUE TITLE
Initialize objects from parent objects

### ISSUE THREAD

**Issue by pepibumur** [tuist/XcodeProj#376]
## Context 🕵️‍♀️
A pattern that I have seen when developers use the library is that they create new objects and forget to add them to the `pbxproj`. As a result, the write fails because those objects are not attached to any project.

## What 🌱
I think we can improve the API to codify that requirement so that developers don't need to think about that. CocoaPods' xcodeproj does it like that and

## Proposal 🎉
For each of the objects that are available, provide a constructor from their parent object:

```swift
let target = try project.addTarget(name: "MyNewTarget")
let configurationList = try target.addConfigurationList()
let configurations = try configurationList.addDefaults()
```

Note that the methods can throw when the object already contains a child *(if it only supports one)*, or has a child that is equal to the one being added.

**Comment by pepibumur** [comment]
What do you think about the idea of making the object constructors internal @yonaskolb?

**Comment by yonaskolb** [comment]
I like the sentiment but I’m not sure about this:
- removing the initializers is a huge breaking change for users
- addition of lots of duplicated and hard to maintain parameters
- the project that these get added to has to then live in each parent somehow. How is memory handled there?

To me this is a sign that the documentation needs to be improve

**Comment by yonaskolb** [comment]
All that said I’m not totally against the idea

**Comment by pepibumur** [comment]
>  removing the initializers is a huge breaking change for users

It is definitively a breaking change, but we can leverage deprecation annotations to give users some time to migrate.

>  addition of lots of duplicated and hard to maintain parameters

Agree. I wish we could do some metaprogramming here to save some code. 

> the project that these get added to has to then live in each parent somehow. How is memory handled there?

That's already handled. Objects that belong to a project have a weak reference to the project objects so they can manipulate them.

> To me this is a sign that the documentation needs to be improve

Agree. We definitively need more documentation for people to know how to use the project. However, I think there's some safety that we can add to the interface to make it easier for users to manipulate their project. Cocoapods xcodeproj for instance provides those methods.

I'll give it a try and open a PR. We can discuss this better with some real examples.

**Comment by jcampbell05** [comment]
I think with something like this these methods could just be sugar to codify and remove steps for developers who just want to generate a project. But for those whom know what they are doing or may want to tackle it a different way can drop down to the raw initializers.

**Comment by mxcl** [comment]
I approve, I made myself a facade layer for using tuist/xcodeproj in [@mxcl/Cake] which does this, however the suggestion sounds like a v7 change, and thus it could be more breaking with the goal of improving the API.

> Note that the methods can throw when the object already contains a child (if it only supports one)

If it only supports one I feel the API would be clearer if it is was a property that you set rather than a method named `addFoo`, then it is clear if you set it *again* that the previous association is lost and there is no need to throw.

As a consumer of this library I feel in general it `throws` too much, in some cases I could not discern why the method would throw. IME there are usually ways to design the API so errors are less frequently possible, and I'm sure the same could be done here.

[@mxcl/Cake]: https://github.com/mxcl/Cake/tree/master/Sources/Model/Base/XcodeProject

**Comment by pepibumur** [comment]
> I think with something like this these methods could just be sugar to codify and remove steps for developers who just want to generate a project.

Exactly. It'd make the process of adding more objects more convenient.

> Then it is clear if you set it again that the previous association is lost and there is no need to throw.

I like this idea. Do you think we should remove the object from the project in that case?

> As a consumer of this library I feel in general it throws too much, in some cases I could not discern why the method would throw. IME there are usually ways to design the API so errors are less frequently possible, and I'm sure the same could be done here.

Interesting, I haven't experienced that myself but it's a totally valid point of view. Would you mind opening an issue with the methods/areas where you think it was confusing seeing a method throwing? I might have designed the API keeping in mind users that don't know much about the structure of Xcode projects. Thinking about it, I think we can assume users know about projects and thus they know what they are trying to do with the API.

**Comment by mxcl** [comment]
> I like this idea. Do you think we should remove the object from the project in that case?

I think frankly, yes that will be necessary, so possibly, if it's too hard for `tuist/xcodeproj` to do we may have to rethink it. I say yes because it seems quite a burden to expect a consumer of the library to know for sure if the previous object had more than one reference or not. If you imagine a large amount of usage spread over multiple functions.

**Comment by pepibumur** [comment]
> I say yes because it seems quite a burden to expect a consumer of the library to know for sure if the previous object had more than one reference or not

Agree. It won't be straightforward though because we'd need to traverse the object that might reference the object being deleted.

> I'll stick it on my TODO.

Awesome :). Thanks for bringing up your experience using the library. It's very valuable 😃

**Comment by pepibumur** [comment]
I dropped this and reducing the throws issue from the Xcode 7 release, which is taking longer than expected.

Here's an idea for this issue:
- We keep the initializers for those developers that want more fine-control on how objects are created and added to the project.
- We add public methods to objects to create child objects. Those methods only list the arguments that are required for the child to be initialized, the other attributes can be set by the developer after the object is created. Some examples:

```swift
let configuration = configurationList.addConfiguration(name: "AppStore")
let scriptPhase = target.addScriptBuildPhase(name: "My Script phase")
let target = project.addTarget(name: "Core", product: .framework)
```
Those child objects get automatically added to the project objects. 

What are your thoughts?

**Comment by pepibumur** [comment]
I'm closing this discussion since there haven't been activity in a year. If this is still relevant for any of you, feel free to re-open it.
