### ISSUE TITLE
Can not write project "you don't have permission to access it"

### ISSUE THREAD

**Issue by BobDeKort** [tuist/xcodeproj#381]
Hello there,

I just started using the library for a personal project and to learn mac os development.
## Context 🕵️‍♀️
The goal of the project is to select an xcode project, select some files somewhere on you computer and then add those files to the Xcode project in a group.

Currently I'm just trying to add a new empty group to the project using the following method:

```swift
private func addNewGroup(project: XcodeProj, with children: [PBXFileElement]) {
        let newGroup = PBXGroup(children: children,
                                sourceTree: .group,
                                name: "Extensions")
        
        project.pbxproj.add(object: newGroup)
        
        do {
            if let projectURL = projectURL {
                try project.write(path: Path(projectURL.relativePath))
                // projectURL.relativePath = "/Users/bob/Desktop/ImportTest/ImportTest.xcodeproj"
            }
        } catch {
            print(error)
        }
    }
```

## What 🌱
The issue I am encountering is that when I try to write the project I get the following error back:
`Error Domain=NSCocoaErrorDomain Code=513 "“contents.xcworkspacedata” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/Users/bob/Desktop/ImportTest/ImportTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x600000c6af70 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}`

I referenced this [issue](https://github.com/tuist/xcodeproj/issues/43) to make the method.
I feel like this should not be this hard to figure out so I must be missing something.

You can find the project here: https://github.com/BobDeKort/XcodeFileImporter

(PS: I would love some documentation and the link on the readme is dead :( )

**Comment by mxcl** [comment]
Since you are using a relative path are you sure about your current-working-directory?

**Comment by pepibumur** [comment]
Hey @BobDeKort the code that you added looks good to me. What I suggest you to do is trying to run that code from a script or Swift package. You can use @mxcl's [swift-sh ](https://github.com/mxcl/swift-sh) to link your script against the xcodeproj dependency.

Looking at the error, I think the problem might be in the permissions that the app has over the user's directory. If the script works, then that's most likely the issue.

**Comment by pepibumur** [comment]
I created a new macOS app project, and **Sandbox App** is enabled by default:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/663605/53613962-08d07580-3ba6-11e9-84fc-928b6f11c873.png">

Try disabling it and running your app again. Let me know if it works :)

**Comment by BobDeKort** [comment]
Hey pepibumur,

Thanks for the fast response.
It seems like that was part of the issue.
I didn't disable App sandbox but I set the "File access> User Selected File" to "read/write"
Now I don't get any error back, but it doesn't add the group either.

I have a busy day at work today so will have a further look in the weekend.

**Comment by pepibumur** [comment]
Great to see that we have figured out one thing. I think the second issue that you mention happens because you are not adding the group to any other existing group. If you don't do so, you end up with a project that contains a group that is not reference by anyone.

If your goal is to add the group to the root directory, you can do something like this:

```swift
let newGroup = PBXGroup(children: children,
                                sourceTree: .group,
                                name: "Extensions")
        
project.pbxproj.add(object: newGroup)
let project = pbxproj.projects.first!
let mainGroup = project.mainGroup
mainGroup.children.append(newGroup)
```
Keep in mind that Xcode will expect your `Extensions` group to be relative to the project root directory.

**Comment by pepibumur** [comment]
@BobDeKort did you manage to add the group? 

With the code snippet that I shared with you it should work. I'm closing this issue for now.
If the example doesn't help feel free to re-open the issue.
