### ISSUE TITLE
Removing files from sources build phase

### ISSUE THREAD

**Issue by andymartinwork** [tuist/xcodeproj#389]
I've been adding files to the source build phase with the following code:

```
let target = pbxproj.targets(named: "MyApp").first!
let sourcesBuildPhase = try target.sourcesBuildPhase()!
_ = try sourcesBuildPhase.add(file: file)
```

When I try to remove a file from the build phase, I notice that there is no `remove` method in PBXBuildPhase. Does this mean it's not possible to remove files?

**Comment by pepibumur** [comment]
Hi @andymartinwork,
You can remove the file from the build phase removing it from [this mutable attribute](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/BuildPhase/PBXBuildPhase.swift#L15). Don't forget to remove the file from the project as well if you don't want it to be in the project anymore. Would you mind trying it and letting me know if it works?

**Comment by pepibumur** [comment]
I'm closing this. If the problem still persists, feel free to create a new issue.
