### ISSUE TITLE
How to add folder in project(V 6.6.0)

### ISSUE THREAD

**Issue by codwam** [tuist/xcodeproj#394]
## Context 🕵️‍♀️
> Provide information that helps with understanding your issue. For example your use case that the project doesn't cover, what you were doing when you found the bug... You can also provide the version of the library that you were using, how you integrated it with your project, the platform version...

ProjectName
 -- Main
 -- Sources
       -- AAA(New folder to added)
           -- BBB.h
           -- BBB.m
           -- CCC.h
           -- CCC.m
  -- Supporting Files
       -- main.m
## What 🌱
> Describe here your issue, a bug you found, an idea that you had, something that  you think can be improved...

I have seen the previous problem, but did not solve it.

` 
           let xcodeproj = try XcodeProj(path: projectPath)
// find your existing group
            let existingGroup = xcodeproj.pbxproj.groups.first { $0.path == "Sources" }!
            
            // append the new group to the existing groups children
           let newGroup = PBXGroup(sourceTree: .group, name: "AAA")
//            existingGroup.children.append(newGroup)// No need
            
            //add the new group to the the list of groups
            xcodeproj.pbxproj.groups.first { $0.path == "Sources" }?.children.append(newGroup)
            
            try xcodeproj.write(path: projectPath)
`

## Proposal 🎉
> Attach your own proposal *(if you have it)*. We'll discuss in on the issue to find the best one that fits into the library.

`pbxproj ` file has been added.
But, it is not shown above xcode.

**Comment by pepibumur** [comment]
Hey @codwam, thanks for reporting this. Would you mind attaching an example project with the Swift code that you execute? It'll be easier to debug the issue there and diagnose what exactly is happening.

**Comment by codwam** [comment]
Sorry I can't give you, but I can provide more information.

### Part of the folder information:
```
AwesomeProject
  -- Sources
    -- AAA(New folder to added)
      -- BBB.h
      -- BBB.m
      -- CCC.h
      -- CCC.m
  -- Supporting Files
    -- main.m
```

### What I want to do is:

Add files below the AAA folder to the Sources folder.

### The code I added is:
```
let xcodeproj = try XcodeProj(path: projectPath)

// find your existing group
let existingGroup = xcodeproj.pbxproj.groups.first { $0.path == "Sources" }!

// append the new group to the existing groups children
existingGroup.children.append(newGroup)
        
try xcodeproj.write(path: projectPath)
```

### The effect of the code is:

> project.pbxproj
```
8B50967A1E38E70900E8FE70 /* Sources */ = {
	isa = PBXGroup;
	children = (
		8B50967B1E38E70900E8FE70 /* Supporting Files */,
		C0EAF320CBE10DA84871C70C55E0BCBA /* AAA */, ### Added!!!
	);
	path = ColorM;
	sourceTree = "<group>";
};
8B50967B1E38E70900E8FE70 /* Supporting Files */ = {
	isa = PBXGroup;
	children = (
		8B50967C1E38E70900E8FE70 /* main.m */,
	);
	name = "Supporting Files";
	sourceTree = "<group>";
};
```

### Missing part of it???
```
// project.pbxproj has added some code, but it lacks the following part
C0EAF320CBE10DA84871C70C55E0BCBA /* AAA */ = {
	isa = PBXGroup;
	children = (
		........
	);
	name = "AAA";
	sourceTree = "<group>";
};
```

Is there a problem with my code?
Can you give me a reference code?

**Comment by pepibumur** [comment]
@codwam I think you are missing adding the object to the project:

```
xcodeproj.pbxproj.add(object: newGroup)
```
Adding a group as a child of another group doesn't imply getting the group added to the project as well. Could you try that and let me know if it works?

**Comment by pepibumur** [comment]
I'm closing it since there hasn't been any answer from April first. If you are still experiencing this issue, don't hesitate to open another issue.
