### ISSUE TITLE
unsync........?

### ISSUE THREAD

**Issue by gubikmic** [tuist/xcodeproj#411]
Hi, I haven't used this project in a while and see that there were some changes.

I think there should be a comment in PBXObjects.swift giving the rationale behind the unsync name. What's the reason behind this?
Also, why is it called 'unsync'? 'Unsync' is a verb, right? Shouldn't it be the adjective 'unsynced'?!

**Comment by pepibumur** [comment]
Hey @gubikmic.

That's a totally valid concern. I missed this one when it was introduced, and I agree it's a bit ambiguous. All variables marked with `unsynced` are not thread safe. They are private and its access is serialized using locks.

I'm not quite sure about unsynced either. What about just underscoring the public name? I've seen that pattern in other places. I'm open to suggestions.

**Comment by azav** [comment]
You are dealing with an abbreviation and “unsync” means unsynchronous (sp?) which is the nature of the action.  I am assuming it is being used as an adjective.  If it were an adverb, it would be unsynchronously. The verb of this is unclear to me, but synchronize is a verb.
