### ISSUE TITLE
Conflict framework name with other framework.

### ISSUE THREAD

**Issue by muizidn** [tuist/xcodeproj#437]
## Context 🕵️‍♀️
This project is amazing! Thank you. But unfortunately it has problem since the library it produces have conflicting name with a library produced by https://github.com/apple/swift-package-manager which is XcodeProj and Xcodeproj respectively.

Its seems that Swift module naming is case insensitive.

## What 🌱
When I try to import XcodeProj, compiler emits error `cannot load module 'XcodeProj' as 'Xcodeproj'` because I also use other framework which its underlying implementation depends on SPM's Xcodeproj

## Proposal 🎉
My current workaround to this problem is to use version 4.3.1 (like Sourcery) where the library name is `xcproj` to avoid conflict. Considering to the future development and integration to community projects, I would love to suggest to add prefix like `TuistXcodeproj` if possible.

**Comment by pepibumur** [comment]
Hey @muizidn, we are glad to hear that you find XcodeProj useful. Unfortunately, I don't think the change that you are proposing is feasible. We recently renamed the project from `xcodeproj` to `XcodeProj` and we'd like to keep it like that.

I suggest opening a ticket on the Swift Package Manager side to have better handling of clashing module names. If you are experiencing this with this module other developers using the Swift Package Manager might have a similar issue.

**Comment by muizidn** [comment]
Ahh, sure. Turns out that I forgot about GitHub fork. Now I just need to point the repository to my forked one. Thank you!
