### ISSUE TITLE
Support Xcode 11 changes

### ISSUE THREAD

**Issue by pepibumur** [tuist/XcodeProj#442]
## Context 🕵️‍♀️
This issue contains all the changes introduced by Xcode 11 that it'd be great to support from XcodeProj:

- [x] Swift Packages
  - Issue: https://github.com/tuist/xcodeproj/issues/438
  - PR: https://github.com/tuist/xcodeproj/pull/439 https://github.com/tuist/xcodeproj/pull/444
- [x] WatchKit containers
	- PR: https://github.com/tuist/xcodeproj/pull/441
- [x] Launch custom commands
  - Context: https://twitter.com/wlisac/status/1136893256543789056
  - Pull request: https://github.com/tuist/xcodeproj/pull/451
- [x] Test plans 
  - PR: https://github.com/tuist/xcodeproj/pull/491
- [x] Development assets. 
  - (These are just in the target's `DEVELOPMENT_ASSET_PATHS` build setting, so nothing to update)
- [x] `platformfilter` in PBXBuildFile: 
  - Pull request: https://github.com/tuist/XcodeProj/pull/494

PBXBuildFile `platformFilter`
```
CC97567A2302C9FA0068CA22 /* Yams in Frameworks */ = {isa = PBXBuildFile; platformFilter = maccatalyst; productRef = CC9756792302C9FA0068CA22 /* Yams */; };
```

## References
- [CocoaPods' Xcodeproj update](https://github.com/CocoaPods/Xcodeproj/pull/687/files)

**Comment by yonaskolb** [comment]
I've been adding things above as I find them

**Comment by pepibumur** [comment]
Thanks @yonaskolb. Highly appreciated 🙏

**Comment by yonaskolb** [comment]
I believe all these items have been completed. I've updated the description with PR links, and closing this now
