### ISSUE TITLE
Dead lock when PBXObjects.delete

### ISSUE THREAD

**Issue by antscript** [tuist/xcodeproj#446]
Call `xcodeProj.pbxproj.delete(object: )` lead to dead lock.

solve:
add
```
defer {
    lock.unlock()
}
```
to **PBXObjects.swift** in **func delete(reference: )** after **lock.lock()**.

**Comment by pepibumur** [comment]
Thanks for reporting this @antscript. Feel free to open a PR with the fix that you suggested. Otherwise, we can look into it.
