### ISSUE TITLE
Getting error: "product dependency 'XcodeProj' not found" when using swift-sh

### ISSUE THREAD

**Issue by pbodsk** [tuist/XcodeProj#454]
## Context 🕵️‍♀️
Thank you for making xcodeproj first of all.

I am taking my first steps into the magic world of writing scripts in Swift and hit a minor speedbump when using `xcodeproj` in combination with [https://github.com/mxcl/swift-sh](swift-sh). More specifically it seems as if the rename from `xcodeproj` to `XcodeProj` does not match the naming in `Package.swift` found in the 6.7 release.

## What 🌱
To reproduce: 

Create a new swift file and add the following to the top (stolen from your README)

```
#!/usr/bin/swift sh

import Foundation
import XcodeProj  // @tuist ~> 6.7.0
```

When running your script you will see this error:

> error: product dependency 'XcodeProj' not found
> warning: dependency 'xcodeproj' is not used by any target

And the fix is to change the import statement referring `XcodeProj` 

_from_
> import XcodeProj  // @tuist ~> 6.7.0

_to_

> import xcodeproj  // @tuist ~> 6.7.0

## Proposal 🎉

I guess you are already in the process of renaming the entire project from `xcodeproj` to `XcodeProj` and you have already fixed it in the `Package.swift` on `master` so I guess this will be solved by itself when you make a new release. I just created this issue in case other lost souls had the same problem.

**Comment by pepibumur** [comment]
> I guess you are already in the process of renaming the entire project from xcodeproj to XcodeProj and you have already fixed it in the Package.swift on master so I guess this will be solved by itself when you make a new release. I just created this issue in case other lost souls had the same problem.

Exactly @pbodsk. I'll keep this one open for now and close it once we release the new version that includes the rename.

**Comment by pbodsk** [comment]
@pepibumur Perfect, makes sense. Thanks!

**Comment by pepibumur** [comment]
We can already close this issue :)
