### ISSUE TITLE
The target name XcodeProj has different case on the filesystem and the Package.swift manifest file

### ISSUE THREAD

**Issue by orj** [tuist/XcodeProj#466]
## Context 🕵️‍♀️
When using XcodeProj in Xcode 11 beta 5 and resolving packages.

## What 🌱
The following warnings are displayed:

```
/Users/.../Library/Developer/Xcode/DerivedData/.../SourcePackages/checkouts/xcodeproj/Package.swift: the target name XcodeProj has different case on the filesystem and the Package.swift manifest file

/Users/.../Library/Developer/Xcode/DerivedData/.../SourcePackages/checkouts/xcodeproj/Package.swift: the target name XcodeProjTests has different case on the filesystem and the Package.swift manifest file

```

## Proposal 🎉
Perhaps the package target name should be `xcodeproj` to match the Git repository name?

**Comment by pepibumur** [comment]
Thanks for the suggestion @orj. I've renamed the repository. It should be safe because GitHub should redirect to the new name automatically.
