### ISSUE TITLE
How to get the resolved build settings of a target?

### ISSUE THREAD

**Issue by acecilia** [tuist/XcodeProj#467]
I have been trying to get the resolved build settings value of an xcode project, but seems like it is not implemented. What I am looking for is the equivalent swift function to https://github.com/CocoaPods/Xcodeproj/blob/2ddf36223dfd4753fb765c82408f9cc215ce6f4e/lib/xcodeproj/project/object/native_target.rb#L54

I am trying to get the value of a build setting that is specified in an xcconfig file, and not inside the `pbxproj`.
Is there any already implemented way of doing this?

Thanks,
Andres

**Comment by kwridan** [comment]
Hi @acecilia 

I don't believe this is implemented - it would certainly be a nice enhancement. 

Depending on your use case if you'd like to get the real resolved settings a slightly more heavy weight approach can be using:

```
xcrun xcodebuild -showBuildSettings -project <project> -target <target>
```

Here's an [example](https://github.com/tuist/tuist/blob/master/Tests/TuistIntegrationTests/Generator/MultipleConfigurationsIntegrationTests.swift#L414) from some of Tuist's configuration tests. This provides resolved settings including platform defaults - the only catch is that it will be a slower approach than parsing settings.

Hope this helps.

Kas
