### ISSUE TITLE
Add support for test plans

### ISSUE THREAD

**Issue by smeshko** [tuist/XcodeProj#484]
## Context 🕵️‍♀️
> Xcode 11 added [test plans](https://developer.apple.com/videos/play/wwdc2019/413), which neither `XcodeProj` nor `XcodeGen` support yet. 

## What 🌱
> Support for test plans has been mentioned in #442, but there doesn't seem to be any other development. 

## Proposal 🎉
> With this issue I'd like to start a discussion about what is still missing (if anything) in order to integrate test plans?

**Comment by pepibumur** [comment]
Thanks for reporting it @smeshko. I'm closing the issue though because there's already [an issue](https://github.com/tuist/XcodeProj/issues/442) created that includes this.

**Comment by yonaskolb** [comment]
Reopening as #442 is closed, so this can be tracked. This issue can track the addition of initialising, reading and writing the test plan files themselves
