### ISSUE TITLE
XcodeProj's dependency on swift-package-manager breaks dependency resolution for consumers of XcodeProj

### ISSUE THREAD

**Issue by elliottwilliams** [tuist/XcodeProj#498]
## Context 🕵️‍♀️
In #492, @pepibumur added SwiftPM as a dependency of XcodeProj. In Package.resolved:

```swift
.package(url: "https://github.com/apple/swift-package-manager", .branch("swift-5.0-RELEASE")),
```

## What 🌱
Unfortunately, this breaks downstream Swift packages that depend on XcodeProj. There's a restriction in SwiftPM that [version-based packages _cannot_ have branch-based dependencies][2].

>  Note that packages which use branch-based dependency requirements cannot be depended-upon by packages which use version-based dependency requirements; you should remove branch-based dependency requirements before publishing a version of your package.

So if I create a package that declares a version requirement on XcodeProj:

```swift
// swift-tools-version:5.1

import PackageDescription

let package = Package(
  name: "repro",
  dependencies: [
    .package(url: "https://github.com/tuist/XcodeProj.git", from: "7.0.0"),
  ]
)
```

it'll fail to resolve:
```
$ swift package resolve
Updating https://github.com/tuist/XcodeProj.git
error: the package xcodeproj[https://github.com/tuist/XcodeProj.git] @ 7.2.2 contains incompatible dependencies:
    swift-package-manager[https://github.com/apple/swift-package-manager] @ swift-5.0-RELEASE
```

This is using the Swift 5.1 toolchain that ships with Xcode 11.0:

```
$ swift -version 
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
Target: x86_64-apple-darwin18.7.0
$ xcodebuild -version
Xcode 11.0
Build version 11A420a
```

## Proposal 🎉

Not sure what a good workaround would be, since SwiftPM doesn't tag versioned releases and instead publishes a branch for each Swift version 😬 

FWIW, [Carthage recently dropped their dependency on SwiftPM][1] due to difficulties supporting multiple Swift versions and working around bugs in SwiftPM itself.

[1]: https://github.com/Carthage/Carthage/pull/2863
[2]: https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md#package-dependency-requirement

**Comment by pepibumur** [comment]
> Unfortunately, this breaks downstream Swift packages that depend on XcodeProj. There's a restriction in SwiftPM that version-based packages cannot have branch-based dependencies.

I'm very sorry for that, I was not aware of this restriction and we should definitively work out a solution for this.

> Not sure what a good workaround would be, since SwiftPM doesn't tag versioned releases and instead publishes a branch for each Swift version 😬

Since they don't tag versioned releases, we can find a replacement package for the SwiftPM. We only use one of its utilities from one of the tests to run command in the system. If  we find a package that provides that utility and that is Linux compatible I'd replace it.

Would you like to push a fix for it @elliottwilliams? Otherwise I can look into it later this week.

Thanks for bringing this up 🙏

**Comment by yonaskolb** [comment]
Yes, would be glad to have SwiftPM removed. It’s a very heavy dependency as well

**Comment by pepibumur** [comment]
> Yes, would be glad to have SwiftPM removed. It’s a very heavy dependency as well

It's only dependency of the [test target](https://github.com/tuist/XcodeProj/blob/master/Package.swift#L21) though.

**Comment by elliottwilliams** [comment]
Sounds good, no worries!

> Would you like to push a fix for it @elliottwilliams? Otherwise I can look into it later this week.

Opened #499

**Comment by pepibumur** [comment]
[XcodeProj 7.3.0](https://github.com/tuist/XcodeProj/releases/tag/7.3.0) has been released 🚀

**Comment by elliottwilliams** [comment]
Thanks for the quick turnaround on this!

**Comment by elliottwilliams** [comment]
One additional wrinkle: The previous versions of XcodeProj that _did_ have SwiftPM can still screw up package resolution. The Package.swift I wrote above works, but if I add XcodeGen 2.10.1:

```swift
// swift-tools-version:5.1

import PackageDescription

let package = Package(
  name: "repro",
  dependencies: [
    .package(url: "https://github.com/tuist/XcodeProj.git", from: "7.0.0"),
    .package(url: "https://github.com/yonaskolb/XcodeGen.git", from: "2.10.1"),
  ]
)
```

it fails again:
```
$ swift package resolve
Fetching https://github.com/yonaskolb/XcodeGen.git
Updating https://github.com/tuist/XcodeProj.git
Updating https://github.com/kylef/PathKit
Updating https://github.com/kylef/Spectre.git
Updating https://github.com/tadija/AEXML
Fetching https://github.com/yonaskolb/JSONUtilities.git
Fetching https://github.com/onevcat/Rainbow.git
Fetching https://github.com/jakeheis/SwiftCLI.git
Updating https://github.com/jpsim/Yams.git
Fetching https://github.com/tuist/Shell
error: the package xcodeproj[https://github.com/tuist/XcodeProj.git] @ 7.2.2 contains incompatible dependencies:
    swift-package-manager[https://github.com/apple/swift-package-manager] @ swift-5.0-RELEASE
```

I think this is because XcodeGen @ 2.10.1 [depends on XcodeProj 7.1.0](https://github.com/yonaskolb/XcodeGen/blob/2.10.1/Package.swift#L19), so SwiftPM's resolver has to consider versions other than the first one it tries to pick. When it considers 7.2.2, it encounters the branch-based dependency and fails.

This is probably a bug in SwiftPM more than a thing XcodeProj needs to deal with here, though. In the meantime, the only workaround I know if is to specify an exact version of XcodeProj in the top-level Package.swift:

```diff
8c8
<     .package(url: "https://github.com/tuist/XcodeProj.git", from: "7.0.0"),
---
>     .package(url: "https://github.com/tuist/XcodeProj.git", .exactly("7.1.0")),
```
