### ISSUE TITLE
PBXBuildPhase type redudancy

### ISSUE THREAD

**Issue by marciniwanicki** [tuist/XcodeProj#512]
## What 🌱
I spotted `PBXBuildPhase` type is exposed publicly twice in the `PBXBuildPhase.swift`:

- First
```swift
    /// The build phase type of the build phase
    public var buildPhase: BuildPhase {
        fatalError("This property must be overriden")
    }
```

- Second
```swift
    /// Returns the build phase type.
    ///
    /// - Returns: build phase type.
    func type() -> BuildPhase? {
        return buildPhase
    }
```

I wonder if there is a reason behind that duplication?

## Proposal 🎉
We could deprecate and later remove the `type()` from the extension.

**Comment by pepibumur** [comment]
Ouch, good catch. I don't see a reason to keep both. Feel free to open a PR adding a deprecation notice to the one that you think is worth deprecating.
