### ISSUE TITLE
Version 7.8.0 Removed

### ISSUE THREAD

**Issue by peymankh** [tuist/XcodeProj#536]
## Context 🕵️‍♀️
Currently a few tools using XcodeProj are failing to be built because version 7.8.0 no longer exists. i.e. Xcodegen

## What 🌱
Version 7.8.0 is removed.

## Proposal 🎉
Is it possible to bring it back?

**Comment by soffes** [comment]
This broke our build. Had to fork XcodeGen and bump the version there https://github.com/yonaskolb/XcodeGen/pull/822

**Comment by peymankh** [comment]
@soffes Epic, one step ahead! Was about to make a PR myself now. Thanks a lot.

**Comment by kikettas** [comment]
Same here with XcodeGen. For the time being, we can roll back to `2.13.0` (that uses Xcodeproj 7.7.0) 👍 Will have a look on that MR @soffes though.

**Comment by yonaskolb** [comment]
XcodeGen 2.15.1 was just released which uses XcodeProj 7.10.0 to work around this. 
Would also like to understand how this happened? 🤷‍♂

**Comment by pepibumur** [comment]
It should be back up. We ran a command by mistake that ended up causing it.
