### ISSUE TITLE
Broken CHANGELOG contributing guideline

### ISSUE THREAD

**Issue by khoi** [tuist/XcodeProj#541]
## Context 🕵️‍♀️
https://github.com/tuist/XcodeProj/blob/912d40cc2ea4a300eff6dd7c6a10b4f4dedbcbec/CHANGELOG.md#L1 

The linked CHANGELOG contributing guideline is broken and I couldn't find the file anywhere.

**Comment by pepibumur** [comment]
@khoi we can update the link to point to [these guidelines](https://tuist.io/docs/contribution/changelog-guidelines/)
