### ISSUE TITLE
“Demo project” is locked for editing and you may not be able to save your changes. Do you want to unlock it?

### ISSUE THREAD

**Issue by fenglh** [tuist/XcodeProj#544]
## Context 🕵️‍♀️
when add UIKit.framework to Build Phase - Link Binary with Libraries  ,  then i can't modify the project 

```
@objc func addUIKitFramework()->Void {
        guard let frameworksGroup = pbxproj.frameworksGroup else {
            return
        }
        let ref = PBXFileReference(sourceTree: .sdkRoot, name: "UIKit.framework", path: "System/Library/Frameworks/UIKit.framework")
        ref.lastKnownFileType = "wrapper.framework"
        pbxproj.add(object: ref)
        frameworksGroup.children.append(ref)
        do {
            try pbxproj.nativeTargets.forEach({ target in
                let frameworksBuildPhase = target.buildPhases.first(where: { $0 is PBXFrameworksBuildPhase })
                _ = try frameworksBuildPhase?.add(file: ref)
                try xcodeproj?.write(path: xcodeprojPath, override: true)
                isBuildPhaseHasUIKit = true
            })
        }catch {
        }

    }
```
## What 🌱
 i get the alert error:
```
“Demo project” is locked for editing and you may not be able to save your changes. Do you want to unlock it?
“Demo project” is currently locked because you are not the owner of the file and do not have write permission.
```

**Comment by pepibumur** [comment]
Hey @fenglh. Thanks for bringing this up. Adding a dependency with a system framework is something that we are already doing [here](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/LinkGenerator.swift#L352) _(for Tuist)_ and that works without causing that error. I'd recommend checking out that implementation and following the same step

**Comment by pepibumur** [comment]
[This](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/ProjectFileElements.swift#L443) is the step that creates the file reference.

**Comment by fenglh** [comment]
@pepibumur good job! you are the best !
