### ISSUE TITLE
.xcschemes get deleted when the project gets saved

### ISSUE THREAD

**Issue by pepibumur** [tuist/xcodeproj#56]
## Context
I read a project and saved it back after doing some changes.

## What
All the `.xcscheme` files got removed:

![image](https://user-images.githubusercontent.com/663605/29724373-8aa54798-89c8-11e7-9f9d-3f679053f5ce.png)

## Proposal
Fix it! 😁

**Comment by rahul-malik** [comment]
@pepibumur - Isn't this as straightforward as **not** deleting the xcschemes folder even if `overwrite` is `true`?

**Comment by pepibumur** [comment]
Exactly. What do you think @rahul-malik ?

**Comment by yonaskolb** [comment]
If we don’t delete the directory then how do we open a project and then delete some schemes and write back?

In this particular issue is the cause that the schemes aren’t being read properly or aren’t being written properly? This needs to be debugged

@rahul-malik this is a different issue to xcodegen. Maybe there we can simply not write (or delete) schemes if none are defined

**Comment by pepibumur** [comment]
I need to dive into the implementation but it might be caused by schemes that are not properly read. Did you have any issue writing schemes with XcodeGen @yonaskolb ?

**Comment by yonaskolb** [comment]
XcodeGen just removes all schemes even if you haven't created any, which in some setups may be undesirable

**Comment by pepibumur** [comment]
When the schemes cannot be parsed we get nil values. That's why when we write back we get the schemes removed. I'll review the way we parse the schemes to make sure it's aligned with Xcode.

**Comment by ilyapuchka** [comment]
@pepibumur any progress with that? I'm working on integrating xcproj to Sourcery but this behaviour is very much undesirable and will be a blocker. If you need help I can look into it. Maybe a quick work around might be not to delete files for unknown schemes (those that were not parsed)?

**Comment by pepibumur** [comment]
There hasn't been any progress so far. The last thing that I remember is that it failed because the schemes where not properly parsed and instead of failing it results in an empty list of schemes. As a consequence the write overrides everything. I think we could fix it by understanding why the parsing is failing, fixing it, and throwing errors instead of silencing them.
What do you think? Would you like to take this over?

**Comment by ilyapuchka** [comment]
Actually the problem that I'm facing is not deletion of schemes, but that they are written in the different format than Xcode, so every time project is saved it overrides all the scheme content and then if you change anything manually in Xcode it overrides it again. This is different, but still annoying, so I will create a different issue for that.

**Comment by pepibumur** [comment]
Is this still happening @ilyapuchka? If not I'll close this issue.
