### ISSUE TITLE
How to add/remote framework for target

### ISSUE THREAD

**Issue by purkylin** [tuist/XcodeProj#561]
```swift
func addFramework(name: String, to target: PBXTarget) {
    if let phase = getBuildPhase(for: "Frameworks", in: target) as? PBXFrameworksBuildPhase {
        let element = PBXFileElement(sourceTree: .buildProductsDir, path: "\(name).framework", name: "\(name).framework")
        let file = PBXBuildFile(file: element)
        phase.files?.append(file)
    }
}
```

Not work, the project filechangs:
> "TEMP_DE02C97D-35B4-4B31-8562-343C44F8E473" /* (null) in Frameworks */,

**Comment by pepibumur** [comment]
Hey @purkylin. Notice that the file element that you are created must be added to the project. Find the PBXGroup of the directory you'd like to add the file to, and add it as a child.

Let me know if that works :)

**Comment by ronnie-codes** [comment]
> 

Not everything you'd like to do to an Xcode project involves adding a file to a group. What if you want to link a framework, but that framework is somewhere else on the filesystem (which is a standard procedure for dynamic libraries)?

**Comment by ronnie-codes** [comment]
> Hey @purkylin. Notice that the file element that you are created must be added to the project. Find the PBXGroup of the directory you'd like to add the file to, and add it as a child.
> 
> Let me know if that works :)

Not everything you'd like to do to an Xcode project involves adding a file to a group. What if you want to link a framework, but that framework is somewhere else on the filesystem (which is a standard procedure for dynamic libraries)?
