### ISSUE TITLE
How to see instance of .xcodeproj in debugger

### ISSUE THREAD

**Issue by carsten-wenderdel** [tuist/XcodeProj#588]
## Context 🕵️‍♀️
I'd like to open a `.xcodeproj` file, parse it and see it's components in the Xcode debugger LLDB.

## Question 🌱
What is the easiest way to see an `XcodeProj` instance in the debugger? Is there something similar to `tuist edit`? Or should I create a Mac project in Xcode and import `XcodeProj` as a dependency?

**Comment by pepibumur** [comment]
Hey @carsten-wenderdel would you mind sharing your use-case? I'm not sure I understand why you need to have `XcodeProj` in LLDB.

**Comment by carsten-wenderdel** [comment]
I once have used the Ruby project https://github.com/CocoaPods/Xcodeproj to open a project file, clone an existing target, change build steps and other things and then save the project. This was quite difficult for me, a mixture of not knowing well the `xcodeproj` file format, the object representation of that file in that Ruby library and the programming language itself. So I had to use a number of `println` to understand how the objects looked like before and after manipulation.

I've now done a spike on `Tuist` to see whether `Tuist` is useful for my team. As Tuist is already doing some "magic" I would like to have the fallback method to additionally manipulate the project files. Writing a script is easier while having a debugger.
