### ISSUE TITLE
Generate an .xcscheme file from the XcodeProj

### ISSUE THREAD

**Issue by iT-Boyer** [tuist/XcodeProj#659]
## Context 🕵️‍♀️
> Provide information that helps with understanding your issue. For example your use case that the project doesn't cover, what you were doing when you found the bug... You can also provide the version of the library that you were using, how you integrated it with your project, the platform version...

## What 🌱
> Describe here your issue, a bug you found, an idea that you had, something that  you think can be improved...

I am working on my company's continuous integration server, and the build process is failing because the server does not have access to schemes in an xcode project.

My research indicates that this problem will be fixed if there is an .xcscheme file with the .xcodeproj file, but for various reasons that can't be generated and checked in ahead of time.

Is there a way to generate this file using XcodeProj?

[more](https://stackoverflow.com/questions/24748553/generate-an-xcscheme-file-from-the-command-line)

## Proposal 🎉
> Attach your own proposal *(if you have it)*. We'll discuss in on the issue to find the best one that fits into the library.

**Comment by pepicrft** [comment]
[There is](https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Scheme/XCScheme.swift). You can create an instance of it and write it to disk where you need it.
