### ISSUE TITLE
invalidateUUIDs() + write() loses references

### ISSUE THREAD

**Issue by timothycosta** [tuist/XcodeProj#683]
## Context 🕵️‍♀️
Trying to make Xcode project deterministic for easy diffing the same as [this issue](https://github.com/tuist/XcodeProj/issues/265).

```
let xcodeproj = try XcodeProj(path: projectPath)
xcodeproj.pbxproj.invalidateUUIDs()
let settings = PBXOutputSettings(projFileListOrder: .byFilename)
try xcodeproj.write(path: projectPath, outputSettings: settings)
```

## What 🌱
If I run the above code on [this project](https://github.com/tuist/XcodeProj/files/8775979/lost.xcodeproj.zip) twice, the first time succeeds. The second time I get an error:
`Error raised at top level: PBXObject with reference "2BAA80704959AADB23CA8DB5F222F967" not found.`

The attached project file has two identical (except for platform) frameworks `Localization` and `Localization Watch`. It seems like XcodeProj thinks they're the same thing, and removes one.

## Proposal 🎉
XcodeProj should be smart enough to realize they're different and not delete the reference.

**Comment by fortmarek** [comment]
Hey @timothycosta 👋 

I agree with you, we'd appreciate any PR for this 🙌
