### ISSUE TITLE
Add support for `ExtensionKit` extension product types (new in Xcode 14)

### ISSUE THREAD

**Issue by kwridan** [tuist/XcodeProj#687]
## Context 🕵️‍♀️

Xcode 14 has introduced a few new frameworks and associated extension product types:

- [`AppIntents`](https://developer.apple.com/documentation/AppIntents)
- [`BackgroundAssets`](https://developer.apple.com/documentation/backgroundassets/)

![app-intents](https://user-images.githubusercontent.com/11914919/172392045-56e7577b-eeda-4733-8b77-ebd81a71efca.png)

![background-assets](https://user-images.githubusercontent.com/11914919/173757732-2f3a9482-82bd-4a48-9174-f987f607fcc0.png)

## What 🌱

- The new extensions have a new product type `com.apple.product-type.extensionkit-extension` which not currently supported by XcodeProj

```plist
		FB2930F2284F86D7004FAF29 /* AppIntentsExtension */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = FB2930FB284F86D7004FAF29 /* Build configuration list for PBXNativeTarget "AppIntentsExtension" */;
			buildPhases = (
				FB2930EF284F86D7004FAF29 /* Sources */,
				FB2930F0284F86D7004FAF29 /* Frameworks */,
				FB2930F1284F86D7004FAF29 /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = AppIntentsExtension;
			productName = AppIntentsExtension;
			productReference = FB2930F3284F86D7004FAF29 /* AppIntentsExtension.appex */;
			productType = "com.apple.product-type.extensionkit-extension";
		};
```

```plist
		FBE4DE842859B1EC00C6A189 /* BackgroundExt */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = FBE4DE8E2859B1EC00C6A189 /* Build configuration list for PBXNativeTarget "BackgroundExt" */;
			buildPhases = (
				FBE4DE812859B1EC00C6A189 /* Sources */,
				FBE4DE822859B1EC00C6A189 /* Frameworks */,
				FBE4DE832859B1EC00C6A189 /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = BackgroundExt;
			productName = BackgroundExt;
			productReference = FBE4DE852859B1EC00C6A189 /* BackgroundExt.appex */;
			productType = "com.apple.product-type.extensionkit-extension";
		};
```

## Proposal 🎉

- Add a new supported `PBXProductType. extensionKitExtension`  that maps to `com.apple.product-type.extensionkit-extension`

## Questions ❓

- Should it be `appIntentsExtension` or something more raw like `extensionKitExtension` ?

Looking at `appExtension`, the same product type is used for several extension types _(e.g. NotificationsServiceExtension, WidgetKitExtension, SiriKit IntentsExtension, etc...)_ - as such calling `appIntentsExtension` may require a breaking change to generalise it the future should new extensions appear that share the same product type 🤐

**Comment by fortmarek** [comment]
> Does this sound reasonable?
 
Yes, I believe so :thumbsup: :eyes:

**Comment by kwridan** [comment]
As I suspected, the same product type is used for a few different extension types, the new product type is also used for the [Background Assets](https://developer.apple.com/documentation/backgroundassets/) extension.

```plist
		FBE4DE842859B1EC00C6A189 /* BackgroundExt */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = FBE4DE8E2859B1EC00C6A189 /* Build configuration list for PBXNativeTarget "BackgroundExt" */;
			buildPhases = (
				FBE4DE812859B1EC00C6A189 /* Sources */,
				FBE4DE822859B1EC00C6A189 /* Frameworks */,
				FBE4DE832859B1EC00C6A189 /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = BackgroundExt;
			productName = BackgroundExt;
			productReference = FBE4DE852859B1EC00C6A189 /* BackgroundExt.appex */;
			productType = "com.apple.product-type.extensionkit-extension";
		};
```

**Comment by freddi-kit** [comment]
Sorry for asking again. when is this change release?

**Comment by kwridan** [comment]
We had a few more PRs pending 😅

This should now be in
https://github.com/tuist/XcodeProj/releases/tag/8.8.0
