### ISSUE TITLE
Add support for Thread Performance Checker scheme diagnostics option

### ISSUE THREAD

**Issue by kwridan** [tuist/XcodeProj#693]
## Context 🕵️‍♀️

In Xcode 14 there's a new "Thread Performance" runtime checker that is enabled by default. This can be configured within the scheme's Run action (`LaunchAction`).

![Screenshot 2022-06-28 at 07 11 02](https://user-images.githubusercontent.com/11914919/176107443-ce242318-818b-4b60-b0b9-1b61db45fbfa.png)

## What 🌱

The new option appears in the `LaunchAction` only if disabled and omitted if enabled (similar to main thread checker).

```diff
    <LaunchAction
       buildConfiguration = "Debug"
       selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
       selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
       disableMainThreadChecker = "YES"
+      disablePerformanceAntipatternChecker = "YES"
       launchStyle = "0"
       useCustomWorkingDirectory = "NO"
       ignoresPersistentStateOnLaunch = "NO"
       debugDocumentVersioning = "YES"
       debugServiceExtension = "internal"
       allowLocationSimulation = "YES">
       <BuildableProductRunnable
          runnableDebuggingMode = "0">
          <BuildableReference
             BuildableIdentifier = "primary"
             BlueprintIdentifier = "FB2F4AA5286220B400DF0A62"
             BuildableName = "TemplateApp.app"
             BlueprintName = "TemplateApp"
             ReferencedContainer = "container:TemplateApp.xcodeproj">
          </BuildableReference>
       </BuildableProductRunnable>
    </LaunchAction>
```

## Proposal 🎉

- Introduce a `disablePerformanceAntipatternChecker` property on `XCScheme.LaunchAction`
- It should be placed immediately after `disableMainThreadChecker` in the generated scheme

## Notes

- This option currently appears under the Run action (`LaunchAction`) only and not under the Test action.

**Comment by leszko11** [comment]
Hi @kwridan!

I can tackle this one :)

**Comment by fortmarek** [comment]
That's great to hear @leszko11! Let us know if you need any help 🙂

**Comment by kwridan** [comment]
Thanks @leszko11 !

Looks like @Bogdan-Belogurov has already submitted https://github.com/tuist/XcodeProj/pull/694
