### ISSUE TITLE
`pbxProject.setTargetAttributes()` isn't thread safe

### ISSUE THREAD

**Issue by brentleyjones** [tuist/XcodeProj#750]
## Context 🕵️‍♀️

I'm adding more concurrency to rules_xcodeproj.

## What 🌱

When calling `pbxProject.setTargetAttributes()` from multiple threads, the mutation of `targetAttributeReferences` isn't guarded, and leads to data corruption or crashes.

**Comment by brentleyjones** [comment]
Actually, it looks like most of `PBXProject` isn't thread safe.

**Comment by kwridan** [comment]
Indeed, it's currently it's not safe to concurrently generate multiple targets of a single project, in Tuist the speed ups are achieves by concurrently generating projects of a single workspace.

**Comment by pepicrft** [comment]
As @kwridan pointed out, `PBXProject` was not designed to be accessed from a multi-thread setup. I'd recommend limiting the access on your end until we can figure out how to evolve the data structure to support parallelism, which I'm afraid won't be possible without radical changes in the data structure, or introduce some internal locking to access it through a single queue. Thoughts @kwridan ?
