### ISSUE TITLE
Unable to add an Embed App Clip phase

### ISSUE THREAD

**Issue by swwol** [tuist/XcodeProj#753]
I'm trying to write a script to embed an AppClip into a project.
There are 2 steps.. Adding the AppClip as a dependency of the main app target, and adding a Copy Files build phase that embeds the AppClip. 

Step 1 appears to be working ok, but step 2 - The Copy Files phase is created but doesn't have any content.

This is what I have so far:

```
func addAppClipEmbedPhase(project: PBXProj, target: PBXTarget) throws {
  guard !target.buildPhases.contains(where: { $0.name() == "Embed App Clip" }) else {
    throw ProjectEditError.error("Target already has a build phase called Embed App Clip")
  }

  let mainGroup = project.projects.first!.mainGroup

  let fileReference = PBXFileReference(
    sourceTree: .buildProductsDir,
    explicitFileType: "wrapper.application",
    path: "AppClip.app",
    includeInIndex: false
  )

  mainGroup!.children.append(fileReference)

  let buildFile = PBXBuildFile(file: fileReference, settings: ["ATTRIBUTES": "RemoveHeadersOnCopy"])

  let phase = PBXCopyFilesBuildPhase(dstPath: "$(CONTENTS_FOLDER_PATH)/AppClips",
                                            dstSubfolderSpec: .productsDirectory,
                                            name: "Embed App Clip",
                                            files: [buildFile],
                                            runOnlyForDeploymentPostprocessing:false)

  project.add(object: phase)
  target.buildPhases.append(phase)
}
```

I suspect I may be missing a step and the buildFile needs to be added somewhere else? But not sure where? Thanks!

**Comment by kwridan** [comment]
I think the missing bit is adding the file reference and build file objects to the project.

```swift
project.add(object: fileReference)
project.add(object: buildFile)
```

XcodeGen and Tuist can be useful references as they both leverage XcodeProj. 

https://github.com/yonaskolb/XcodeGen/blob/5a34c489e16eed6b7d43ee0064b3525b0d11f1c0/Sources/XcodeGenKit/PBXProjGenerator.swift#L1192

https://github.com/tuist/tuist/blob/4fdcf9d2b75fc16a4426a3f9dd7f30ca9d0dc3b6/Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift#L541

Hope this helps

**Comment by kwridan** [comment]
I've tried out the snippet in a sample and hit the same error, looks like there's a small type error in the build file attributes, where it should be an array of string flags rather than a single string/

```swift
 let buildFile = PBXBuildFile(file: fileReference, settings: ["ATTRIBUTES": ["RemoveHeadersOnCopy"]])
```

Note, if you are modifying a project that already has both targets within it, existing file references can be used rather than creating new ones:


```swift
func addAppClipEmbedPhase(pbxProj: PBXProj, appTarget: PBXTarget, appClipTarget: PBXTarget) throws {
    guard !appTarget.buildPhases.contains(where: { $0.name() == "Embed App Clip" }) else {
        throw ProjectEditError.error("Target already has a build phase called Embed App Clip")
    }

    let embedAppClipsBuildPhase = PBXCopyFilesBuildPhase(
        dstPath: "$(CONTENTS_FOLDER_PATH)/AppClips",
        dstSubfolderSpec: .productsDirectory,
        name: "Embed App Clip"
    )

    pbxProj.add(object: embedAppClipsBuildPhase)
    appTarget.buildPhases.append(embedAppClipsBuildPhase)

    guard let appClipFileReference = appClipTarget.product else {
        throw ProjectEditError.error("AppClip file reference is not available")
    }

    let buildFile = PBXBuildFile(file: appClipFileReference, settings: ["ATTRIBUTES": ["RemoveHeadersOnCopy"]])
    pbxProj.add(object: buildFile)
    embedAppClipsBuildPhase.files = [buildFile]
}
```

**Comment by swwol** [comment]
Thank you so much! Just tried that and its working perfectly now
