### ISSUE TITLE
`XCSchemeManagement` reads from path are unstable

### ISSUE THREAD

**Issue by kwridan** [tuist/XcodeProj#756]
## Issue

It appears creating `XCSchemeManagement` from a path can yield an unstable order for the `schemeUserState` internally which leads to two identical `XCSchemeManagement` not reporting they are equal.

## Details

- `XCSchemeManagement` decodes its values from a plist file
- `schemeUserState` is a dictionary within the plist
- This is then internally converted to an array of `[XCSchemeManagement.UserStateScheme]` without any sorting 
- This results in the order of elements within the final `XCSchemeManagement` being unstable for the same plist file

## Reference

_Originally posted by @JCSooHwanCho in https://github.com/tuist/tuist/issues/5154#issuecomment-1518671235_

**Comment by JCSooHwanCho** [comment]
I made [PR](https://github.com/tuist/XcodeProj/pull/757) about it. Could you check it please?

**Comment by JCSooHwanCho** [comment]
Oh, It's duplicate with your [PR](https://github.com/tuist/XcodeProj/pull/758)
