### ISSUE TITLE
Creating a new release

### ISSUE THREAD

**Issue by BarredEwe** [tuist/XcodeProj#789]
## Context 🕵️‍♀️
Recently, a PR https://github.com/tuist/XcodeProj/pull/784 was added for **Swift Package Plugins**. This revision is needed for XcodeGen https://github.com/yonaskolb/XcodeGen/pull/1374 and Tuist https://github.com/tuist/tuist/pull/5299. 

## What 🌱
To use the improvements, we need to create a new release 😊

**Comment by luispadron** [comment]
Released! https://github.com/tuist/XcodeProj/releases/tag/8.13.0

**Comment by luispadron** [comment]
Thanks for your first contribution btw!
