### ISSUE TITLE
Cannot remove remotePackage

### ISSUE THREAD

**Issue by kevin-kp** [tuist/XcodeProj#802]
## Context 🕵️‍♀️
We are trying to change the version of a package using XcodeProj. We are doing this by removing the package and readding the swift package.

## What 🌱
On 8.12.0, this works without any issues. However, since https://github.com/tuist/XcodeProj/pull/799 it seems that it isn't possible anymore to remove a swift package.
This is because the setter reads the existing packages when the value is changed. This means that it is only possible to add new packages:
```
var finalReferences: [PBXObjectReference] = packageReferences ?? [] // this contains the removed package
let newReferences = newValue.references()
for reference in newReferences {
    if !finalReferences.contains(reference) {
        finalReferences.append(reference)
    }
}
packageReferences = finalReferences
```

**Comment by art-divin** [comment]
Thank you very much @kevin-kp 👋🏻 

I am sorry I did not foresee this behaviour. 🙇🏻

**Comment by kevin-kp** [comment]
@art-divin No problem 😄 It should be fixed once the PR is merged 😄
