### ISSUE TITLE
Incorrect name of the target product returned from `productNameWithExtension()`

### ISSUE THREAD

**Issue by mikeger** [tuist/XcodeProj#820]
## Context 🕵️‍♀️
As an author of [XcodeSelectiveTesting](https://github.com/mikeger/XcodeSelectiveTesting) I've been trying to integrate it for fun with [Wire-iOS](https://github.com/wireapp/wire-ios) project.

This project has several libraries, amongst those you can find `WireCanvas` project. This project has a target called WireCanvas that emits a framework. 

## What 🌱
When parsing `WireCanvas` project, XcodeProj is returning `Canvas.framework` from `productNameWithExtension()`. Correct name of the product is `WireCanvas.framework`

## Proposal 🎉
I tried to fix the issue but was not sure what was causing this behavior. There must be some misconfiguration in the WireCanvas project, but from Xcode side I only see `WireCanvas.framework` in other project linked frameworks phase and as a product name

**Comment by mikeger** [comment]
@kwridan thanks so much for the reply. This sounds reasonable, adding support for `xcconfig` resolution might be too big of a feature for a GitHub issue :) 

Would it make sense to enhance the documentation for `productNameWithExtension()` (any other?) method so people using it would have reasonable expectations? I can propose a small change for this if you think this is appropriate.

**Comment by kwridan** [comment]
Sure that sounds like a reasonable change, this contribution would be welcome! thanks @mikeger

**Comment by mikeger** [comment]
@kwridan I created the PR, thanks for your support.
