### ISSUE TITLE
error: (DecodingError) keyNotFound(CodingKeys(stringValue: "compatibilityVersion", […]), […]))

### ISSUE THREAD

**Issue by F1248** [tuist/XcodeProj#837]
## Context 🕵️‍♀️
- Xcode version: `16.0 beta 5 (16A5221g)`
- Xcode project format: `Xcode 16.0`
- Periphery version: `2.21.0`

I'm trying to scan my project with [Periphery](https://github.com/peripheryapp/periphery) which uses XcodeProj. When I run `periphery scan` it says the key `compatibilityVersion` was not found, which is correct, my `.xcodeproj` file doesn't contain this key.
It seems that since project format `Xcode 16.0` this key should no longer be included. When I downgrade the project format to `Xcode 15.3`, it adds this key, but as soon as I revert it back to `Xcode 16.0`, it removes it again.

## What 🌱
`error: (DecodingError) keyNotFound(CodingKeys(stringValue: "compatibilityVersion", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"compatibilityVersion\", intValue: nil) (\"compatibilityVersion\").", underlyingError: nil))`

## Proposal 🎉
Don't expect the key `compatibilityVersion` if the `objectVersion` is >= `73`.

**Comment by pepicrft** [comment]
Thanks @F1248 for reporting this. Seems like Xcode 16 uses a slightly different schema when `objectVersion` is above the value that you pointed out. Would you like to take a stab at fixing it? If you add me as a reviewer, I'd be happy to review it and get your changes landed

**Comment by F1248** [comment]
> Thanks @F1248 for reporting this. Seems like Xcode 16 uses a slightly different schema when `objectVersion` is above the value that you pointed out. Would you like to take a stab at fixing it? If you add me as a reviewer, I'd be happy to review it and get your changes landed

@pepicrft, I'm sorry, but I can't fix this myself. I would be delighted if someone else could.

**Comment by F1248** [comment]
@thanhbinh01234, thank you for fixing this!
I'll close this issue as soon as the fix is used in a released version of Periphery, so I can verify that it works for me.

**Comment by kimdv** [comment]
@pepicrft @F1248 I've opened a PR and started the work :)
