### ISSUE TITLE
`error: (DecodingError) typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "preferredProjectObjectVersion", intValue: nil)] […]))`

### ISSUE THREAD

**Issue by F1248** [tuist/XcodeProj#861]
## Context 🕵️‍♀️
- Xcode 16.1 beta 2 (16B5014f)
- Xcode project format: `Xcode 16.0` (`objectVersion = 77`)
- Periphery 2.21.1
- XcodeProj 8.24.1

project.pbxproj:
```
// !$*UTF8*$!
{
	objectVersion = 77;
	objects = {
[…]
/* Begin PBXProject section */
		XXXXXXXXXXXXXXXXXXXXXXXX /* Project object */ = {
			isa = PBXProject;
			[…]
			preferredProjectObjectVersion = 77;
			[…]
		};
/* End PBXProject section */
[…]
	};
	rootObject = XXXXXXXXXXXXXXXXXXXXXXXX /* Project object */;
}
```

## What 🌱
When I try to scan my project with [Periphery](https://github.com/peripheryapp/periphery), that uses XcodeProj, with `periphery scan`, I get this error message:

`error: (DecodingError) typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "preferredProjectObjectVersion", intValue: nil)], debugDescription: "Expected to decode Int but found a string instead.", underlyingError: nil))`

It seems that for my project, #854 doesn't work as expected.

**Comment by F1248** [comment]
@pepicrft

I created [this project](https://github.com/user-attachments/files/17189695/Test.zip) newly using Xcode 16.1 beta 2 (16B5014f):
`Create New Project…` → `Multipl`→ `App`
```
% cd Test
% periphery scan --setup
Welcome to Periphery!
This guided setup will help you select the appropriate configuration for your project.

* Inspecting project...

error: (DecodingError) typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "preferredProjectObjectVersion", intValue: nil)], debugDescription: "Expected to decode Int but found a string instead.", underlyingError: nil))
```

**Comment by aksh1t** [comment]
I can reproduce this as well on a fresh iOS project created with Xcode 16 (16A242d).

**Comment by pepicrft** [comment]
I opened [a PR addressing the issue](https://github.com/tuist/XcodeProj/pull/862)

**Comment by aksh1t** [comment]
Can confirm your PR fixes the issue! Thanks for the quick fix!
